### ISSUE TITLE
Support for syncing QS across devices

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#1158]
It would be good if you could specify the location of the App Support folder for QS so that you could move it to say ~/Dropbox and use the same data across devices.

In doing this, we should also ensure that QS gives up gracefully on indexes/paths that don't exist in the catalog etc.

Interestingly… (what made me make this issue right now) is that there's already a `extern NSString *QSApplicationSupportPath;` defined in QSPaths.h which is taken as either the app support folder, or a path saved in the user defaults. If we were to set this path in the user defaults, then most of QS would take care of itself…
Seems like Alcor already thought of this as well. Spooky

**Comment by borgo1971** [comment]
Even I think that import/export future for QS settings could do much part of the job, I think even that cloud syncing could be even nicer and should be rivalutate. Since the opening of this thread are past about 10 yaers, and may things are changed. Many apps and service are become synced even between different platforms. And about cloud services, iCloud now is a free service for all Mac users, and QS is a Mac only application, so I think it should be the reference cloud service.
I agree it could not be simple to have a consistent synchronization with different systems, however I believe that the topic deserves further study.

**Comment by pjrobertson** [comment]
Thanks borgo1971 for the reply. We will re-open this issue and continue to explore it.

Current suggestions/things to explore:

* Add an export/import feature to export them import Quicksilver settings via a file
* Add sync using iCloud
* Allow syncing via another app

**Comment by borgo1971** [comment]
it may be superfluous, but I would like to clarify that both the import / export procedure and the synchronization may not affect all preferences and "Application Support". For example, it seems obvious to me that the catalog is not transferred between different machines.
So it should not be the same as coping entry preference and support file between machines.
