### ISSUE TITLE
Proxy object children

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#1420]
When implementing “synonyms”, I used `loadChildrenForObject:` to make it appear as if the synonym had the same children as the resolved object. So, for instance, right arrowing into a synonym for an application will show its recent documents instead of the application.

Is there any reason not to modify proxy objects so they present the resolved object's children as their own? (If you just want to know what the resolved object is, you can always reveal it with “Select in Command Window”.)

I thought of this when creating `QSUserDefinedProxySource`, but now I have a concrete reason: `Proxy ⇥ Search Contents` doesn't always work, and it should.

**Comment by skurfer** [comment]
Another idea for the specific use case I mentioned…

The **Search Contents** and **Show Contents** actions could just check to see if they were passed a proxy object and show the resolved object’s children instead.

**Comment by pjrobertson** [comment]
I just tried implementing this, but passing the `resolvedObject` info through in `QSProxyObject.m`. 

The outcome is that when searching the catalog, any proxy object that comes your way will be resolved, severely slowing down Quicksilver. For example:

1. You type "cw" into the 1st pane
2. The 'Current selection' proxy object appears, and is attempted to be resolved (so as to show the actual object)
3. The resolve times out after 5s because there's nothing to select
4. Then the search switches to "Current Web Page (Safari)"
5. This resolves slowly / times out (because Safari isn't running) etc.
6. etc.

The solution to overcome this would be to only resolve certain objects which we know can be resolved quickily. E.g. 'Latest Download' etc.
