### ISSUE TITLE
Option for delete key to delete last character instead of entire entry

### ISSUE THREAD

**Issue by sinewave** [quicksilver/Quicksilver#177]

**Comment by skurfer** [comment]
As I said on the pull request’s discussion, I’ll go along with making this the default, but I have to say I *really*, *really* don’t get it. I mean, you’re replacing this:

  1. Typo
  2. ⌫
  3. Type abbreviation again (most likely effortless due to muscle memory)

with this:

  1. Typo
  2. Press ⌫ enough times to remove the mistake
  3. What did I mean to type?
  4. What is left undeleted?
  5. What is the difference between those?
  6. Type the difference (for which you have no muscle memory)

**Comment by pjrobertson** [comment]
Thanks for chiming in @hmelman over on the pull request.

Rob - what's your argument for every other search field (including Spotlight and I'm assuming other app launchers) using 'delete removes a single character'?

What you outlined in your second set of steps is what I have to do everywhere (URL bar, Google, Spotlight, Contacts...).
I think you have a case arguing that it might not be best for short strings where you might be typing abbreviations, but I think deleting the whole string and starting from scratch is more of a 'power user' thing, and is why it should still be an option, just not the default

**Comment by skurfer** [comment]
> Rob - what's your argument for every other search field (including Spotlight and I'm assuming other app launchers) using 'delete removes a single character’?

Those are text boxes, just like Quicksilver is in text-entry mode. The behavior makes sense in those contexts because you’re “editing” text.

You can also see what you’re working on, where in QS you’d have to parse out which characters are highlighted in the first pane, and they could jump around as you add/remove characters if the result changed. It just never felt like “entering text” to me.

> I think you have a case arguing that it might not be best for short strings where you might be typing abbreviations

What else would you be typing when searching with Quicksilver? 😃 

> but I think deleting the whole string and starting from scratch is more of a 'power user' thing, and is why it should still be an option, just not the default

Maybe it would help to know that I rarely need to type more than 2 characters to find what I’m after, and 5 characters is like a crazy edge case that annoys me. So losing all of it and starting over is pretty low cost.

Is that “power user” behavior? I thought that was the whole point of this app!

Anyway, no one needs to convince anyone else here. I’ve already said I’ll go along with the new default.
