### ISSUE TITLE
Add "Sort by Date" & "Sort by Size" menu items to results menu with keyboard shortcuts

### ISSUE THREAD

**Issue by sinewave** [quicksilver/Quicksilver#178]
Update: I have edited this issue with an updated title and description to reflect what i think would be a better implementation

From Comment #3:
"The best way to implement this i think would be to add "Sort by Date" and "Sort by Size" menu items to the results menu which already has sort by name, score. You would also need to assign each of the sort options a keyboard shortcut similar to Task Viewer, Clipboard, or any other menu item.

This also makes the workflow a lot easier in that you dont have to decide how you want to sort the results before you display them which i always found to be in clunky in other launchers. Instead you get your results and then you can choose to sort them any way you want by clicking on the appropriate menu item or hitting the keyboard shortcut. This would also allow you to change sort options on the fly instead of having to go back and then use a diff modifier key to enter the result set with a new sort option."

Original Comment:
Ability to sort folder contents by modified, size, name, etc. by pressing an additional key when right arrowing into a folder similar to how showing hidden files by Option-arrowing into a folder works. Extremely useful for things like downloaded files, etc..

**Comment by joshgold22** [comment]
Since this is mainly useful for file folder scanning, I think we'd want to distinguish between date added, created and modified.  E.g., one version would make is very quick to open a file I just downloaded to my Downloads folder.  Another would make it easy to pull up the files I'm working on in a large programming project.

**Comment by petonic** [comment]
Has there been any update to this?  I'd really enjoy sorting by modification or created date in the results.  It would help staying in QS mode instead of going to Finder.

**Comment by skurfer** [comment]
I’ve always been against this because so many things don’t even have dates or sizes.

That doesn’t mean it won’t happen. I only speak for myself and this project is open to anyone (and there are other regular contributors). I just want everyone to be aware that I have no plans to ever look at this. If this feature really matters, you might need to do more than ask for it. :smiley:

**Comment by petonic** [comment]
Fair point, Rob.  How about this?  If you do that, or better yet (perhaps), expand the Spotlight Plugin's "Smart Folder" functionality to yield results (sorted by ModTime?) then I'll donate $50 to you or to the QuickSilver cause.

To be fair, it's a win win for me, because I should've already donated the money.   <<<SCRATCH THAT>>>  I just donated $50 to donate@qsapp.com.  I love this utility.

In any case, to go back to my specific use case...

I have a Smart Folder called "1Day" that gives me a list of all files that were modified in the last day.  Then, I have that view sorted by "Date Modified".  This way, when I'm hammering out an email, I can bring up QS, execute my Smart Folder, and go into the results, find the last file, and invite "Paste in current application" and I'm good as done.

**Comment by skurfer** [comment]
> expand the Spotlight Plugin's "Smart Folder" functionality to yield results (sorted by ModTime?)

If sort by time works anywhere, it’ll work there, too. But when I last overhauled the Spotlight plug-in, I looked right-arrowing into smart folders. The problem is that the search stored in a smart folder uses a completely different syntax from searches performed in code. You’d need something that knew how to translate, which is likely to be pretty flakey.

> I just donated $50

Appreciated.

> In any case, to go back to my specific use case…

Like I said, right-arrowing (or the Show Contents action which is the same thing) is problematic, but I’m no longer opposed to sort by date getting implemented someday. But to quote @HenningJ above:

> Also, think about what happens to the objects that appear in the result list, but can't be sorted with a specific sorting option, while others in the result list can be? Should the by omitted? Or just be put at the end of the list?

I think you should probably have the option to sort both directions, but if things were at the end of the list initially, reversing the order would put all the undated items at the beginning. That’s a case for omitting them, I think.

**Comment by sinewave** [comment]
As the creator of this ticket, 4yrs ago :scream:, i still find myself wishing for this feature on a daily basis.

To address some of the concerns above regarding objects that dont have a date I think this can be pretty easily solved by only implementing this feature when file browsing . My use case for this would be solely for arrowing into a file directory to view the most recently modified files/folders. 

If i remember correctly @pjrobertson actually implemented a few lines code to do this very thing but i dont think it was ever released. It simply involved holding down a specific key (Cmd or Alt?) while arrowing into a directly and then the contents would be sorted by most recently modified desc. 

I would be 100% happy if only that single feature was implemented as sorting of size or sorting by date asc is a *much smaller* usecase.

Any chances :pray:

**Comment by skurfer** [comment]
Something to think about. There are some contexts where you might want a different date. Some examples:

* Looking at recent documents, it would be nice if they were sorted by date opened.
* Looking at history, it would be nice if things were sorted by order used.

But we wouldn’t want to clobber the actual date because it would screw up the order in the normal context.

**Comment by sinewave** [comment]
Saw the notification come up a couple of weeks back and thought I would give it another shot. The ability to simply hold down a key when navigating into a dir is something I would use throughout the day.

Five years later, still pitching to get this feature implemented :)

**Comment by tiennou** [comment]
I have a tentative branch for this BTW. I'll try to cleanup and publish so you have a baseline.
