### ISSUE TITLE
Request / Question: Search clipboard history?

### ISSUE THREAD

**Issue by benbernard** [quicksilver/Quicksilver#1985]
According to this issue: https://github.com/quicksilver/Quicksilver/issues/1737 you can search clipboard history using Clipboard History -> Show Contents.

However in the most recent version of quicksilver / clipboard plugin, the show contexts action doesn't show up for the clipboard object (only 'Show Contents Menu' which doesn't seem to do anything).

Is this still possible? Am I just missing it? Thanks!

**Comment by ovizii** [comment]
Sorry guys but I don't get this.
- my clipboard is full,
- it shows items in catalogue => QS => clipboard/shelf 

Yet I can't seem to figure out how to search my clipboard. 
Feeling a bit blonde right now but is there a video how-to somewhere?

**Comment by tiennou** [comment]
@ovizii If the checkboxes for "Shelf & Clipboard" and its children are all checked in the Catalog pref pane, you should be able to search for "clip" in the first pane and get "Show Clipboard", "Clipboard" (which looks broken btw), and "Clipboard History", which is →-able and has the contents you're looking for, and fuzzy search works here.

If you want, you can build a trigger for this, by entering "Clipboard History > Show contents", then ⌃↩ (which will give you a "Show contents of Clipboard History" command in the first pane), and choose "Add Trigger > whatever trigger type you want". The Triggers pref pane should come up for the additional customization.

Granted, you can't search directly for the items in the Clipboard straight from the interface because they don't appear in the returned objects here. No idea why, but I wager that they might change too often and thus never match, or they're somehow not indexing correctly...

**Comment by skurfer** [comment]
> Granted, you can't search directly for the items in the Clipboard straight from the interface because they don't appear in the returned objects here. No idea why, but I wager that they might change too often and thus never match, or they're somehow not indexing correctly…

That was the case for a ling time, but someone (@pjrobertson?) recently added “Shelf Contents” and “Clipboard Contents” catalog presets that will put things in the top-level catalog, if you’re into that sort of thing.

**Comment by tiennou** [comment]
Then I wasn't able to get it to work consistently. I mean, my currently-last (a gist URL) Clipboard entry doesn't appear when I search for its gist ID). I can see a few of the older ones, but the most recent aren't here.

**Comment by ovizii** [comment]
@tiennou Hoory! I finally got it working with your help. 

Except, now this is how I am using it: 
press the trigger, the window pops up, I type what I am searching for, it finds it but how do I set "paste into current application" as the default action for the result?

**Comment by tiennou** [comment]
@ovizii You'll have to fiddle with the rank settings in "Preferences > Actions" for that. Take note of what the current default is for text objects at the moment in the interface (I have "Calculate" first for text here), find the Paste action in the list, drag it one level above the current default. That should do it.

Be careful, because those action ranks are global, so you're effectively changing every text object default action to this one.

**Comment by ovizii** [comment]
gee, for such a simple thing, this is quite complicated ;-) 
I'm looking to paste the result => http://screencast.com/t/ScfeeAZU 

But I can't find that one in my actions :-( => http://screencast.com/t/q8yv252fLvUN

**Comment by tiennou** [comment]
Maybe try looking at the complete list ? The "By type" selection is really just a convenience, and sometimes the action you're looking for doesn't actually appear where you'd expect it to. But I'm pwwetty sure it has to be in here ;-).

**Comment by ovizii** [comment]
Now I am completely confused. I assumed by type was the complete list? 
The only other choice is by plugin? => http://screencast.com/t/1yLYNaTU
So if I select by plugin, the select all plugins and set paste to top, it will affect the complete ranking not only its rank when it comes to text.

Above you said: Take note of what the current default is for text objects at the moment in the interface 
So if I select all plugins how can I take note what's set for text objects? :-( 
Sorry for all this hand-holding you're doing but I'm so lost.

**Comment by tiennou** [comment]
Sorry, I wasn't clear. The complete list is "By Type > All actions". I added the "Take note" step so you just override the actions that work on text, because dragging paste all the way to the top could have unforeseen consequences.

**Comment by ovizii** [comment]
FInally! I got it working :-) 
Thanks so much for the assistance.
