### ISSUE TITLE
Quicksilver hangs when searching contacts

### ISSUE THREAD

**Issue by kaarlows** [quicksilver/Quicksilver#2015]
In the last 2 or 3 versions of Quicksilver, I'm having an issue with it crashing every time the search results pulls up the first option being a contact. 
For example, when searching "bel", I have a contact name Belinda, but I'm trying to search for Bellhop app. 
If Belinda comes as the first option on my search, and I try to use the directional buttons on my keyboard to look the other search results, Quicksilver hangs up and stop responding me. So I have to use Force Quit for it.

**Comment by pjrobertson** [comment]
@kaarlows  - this issue was created a while back, and we haven't made any progress on it, sorry.

Can you please try the latest version of Quicksilver, and if you're still facing this this issue, can you please re-open this issue then confirm where your contacts are stored (iCloud/computer) and whether the hang is related to internet-fetches.
