### ISSUE TITLE
When using Colemak keyboard, can't input letter O

### ISSUE THREAD

**Issue by slambert** [quicksilver/Quicksilver#2027]
Switch to Colemak, Invoke Quicksilver. The O key (or ":" on QWERTY) doesn't respond.

May be related to this: https://github.com/quicksilver/Quicksilver/pull/1147

**Comment by slambert** [comment]
As I used Colemak more and more this just went away. I think the keyboard layout was switching back and forth between applications and causing weirdness. Closing, because (selfishly) it's solved for me...

**Comment by timvisher** [comment]
@slambert it's definitely a known issue with switching soft-layouts. if you don't have triggers assigned to keys then the easiest way to fix it is to re-launch 𝑄uıcĸsılⅴεʀ once you've switched to the desired layout.

If you _do_ have triggers defined, then you're out of luck for some indeterminate amount of time. All OS X applications that I use that allow me to define custom hotkeys suffer from the same problem, and I would guess something internal to OS X changed at some point and now we're all reaping the fruits of that.

As a workaround, what I've done for my most important triggers is to define them once in each soft-layout so that they remain consistently available.

This causes you to run out of keys twice as fast, unfortunately, so I only do it for my most important triggers.
