### ISSUE TITLE
Symlinked applications catalog error (1.2.2)

### ISSUE THREAD

**Issue by leoj3n** [quicksilver/Quicksilver#2030]
Encountering the issue #1882 was supposed to fix.

OS X 10.8.5
Quicksilver 1.2.2

I have tried rebuilding the catalog, tried creating a copy of the "Applications (User)" preset with depth of 1 and no type, and tried disabling Finder/Path Finder plugins to no avail.

Regression?

**Comment by skurfer** [comment]
I just tried `brew linkups python3` to create some symlinked applications in `/Applications` and they get indexed correctly. Are your symlinks in `~/Applications`? (Not that is should matter.)

**Comment by leoj3n** [comment]
Do you mean `brew linkapps`? Yes my symlinks are in `~/Applications`.

**Comment by skurfer** [comment]
> Do you mean `brew linkapps`?

Yeah. Autocorrected.

> Yes my symlinks are in `~/Applications`.

I tried moving one there and it worked just as well. All the code involved in that should be OK on 10.7+.

Are you getting useless objects in the catalog, or are the linked apps not appearing at all? Do you see them in the Catalog prefs if you select “Applications (User)” and open the Info panel, then go to Contents?

**Comment by leoj3n** [comment]
No useless objects. The symlinked application are appearing. Same problem regarding "Applications" as "Applications (User)".

![catalog](https://cloud.githubusercontent.com/assets/990216/6281038/a1ca6e5e-b87d-11e4-84fc-d81132681789.png)

Note: Same result if selecting "Applications" or "Applications (Catalog)".
![applications](https://cloud.githubusercontent.com/assets/990216/6281048/c592eac8-b87d-11e4-8d16-ef7a8d162a2e.png)

![macvim](https://cloud.githubusercontent.com/assets/990216/6281049/c7e53b14-b87d-11e4-98d6-0e0451004137.png)

I should also mention Quicksilver has been crashing every now and then. Maybe I need to obliterate the catalog by hand and let it rebuild it? Maybe a plist? Dunno. I'll try reinstalling when you give me the go-ahead unless you want me to troubleshoot further.

**Comment by skurfer** [comment]
> Maybe I need to obliterate the catalog by hand and let it rebuild it? Maybe a plist? Dunno. I'll try reinstalling when you give me the go-ahead unless you want me to troubleshoot further.

About the only thing useful is clearing the caches. I usually do it Terminal. Quit Quicksilver, then run

    rm -r ~/Library/Caches/*Quicksilver

and start it again.

It sounds like the Reveal action is running instead of Open, but I can see the Open action selected by default in your screenshots. I assume the same thing happens with Finder set as the handler for files? What version of Path Finder are you running?

**Comment by leoj3n** [comment]
Upgraded `Path Finder.app` to the latest version and ran `rm -r ~/Library/Caches/*Quicksilver` but still opens when set as the default file handler. Changing the file handler to `Finder.app` does fix the issue.

**Comment by skurfer** [comment]
I’m still on 6 and don’t use it enough to justify buying the upgrade. I can’t reproduce it in Finder or Path Finder.

Are there any preferences in the new version that look like they might control this behavior?

**Comment by leoj3n** [comment]
Not that I can tell..

**Comment by skurfer** [comment]
Hmmm. Maybe something needs to be changed around in [the Open function for Path Finder][1]. I’m afraid I can’t experiment unless I upgrade, which I don’t really plan to do. All the Finder bugs that were annoying me were fixed in 10.9 (and in that same version of OS X, they introduced the ability to treat a second display as a space and Path Finder didn’t handle that very well).

[1]: https://github.com/quicksilver/PathFinder-qsplugin/blob/master/QSPathFinderProxy.m#L26

**Comment by skurfer** [comment]
OK, I tried the trial of PF 7 and ended up upgrading. I just saw this happen with a symlinked application, so maybe I’ll be able to track it down.

**Comment by leoj3n** [comment]
Will be interesting to hear what the outcome is :8ball:

**Comment by skurfer** [comment]
Fixed by #2142
