### ISSUE TITLE
System overload due to QS+Evernote

### ISSUE THREAD

**Issue by VBoudry** [quicksilver/Quicksilver#2051]
Today I had to restart my mac (under OSX 10.10.3 if it matters), which became irresponsive.
I though it was due to Evernote, but a look console after the restart showed bunches (3424 in 1 second) of:

19/04/2015 10:25:47,374 Quicksilver[413]: AppleEvents: Send port for process has no send right, port=( port:44431/0xad8f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) QSCatalogEntry scanQueue: QSPresetEvernoteTags

I don't know what to do with that, but I hope someone here does...

Best regards,
Vincent Boudry.

**Comment by skurfer** [comment]
I’ve seen messages like that from the iTunes plug-in since OS X 10.9 was released. Other than knowing that it has to do with Scripting Bridge, I haven’t been able to find any cause, but I also haven’t found any practical problems that result.

It might be the large number of messages in this case, or it could have been something unrelated and the messages are a coincidence.

Does it happen regularly? If so, try disabling the Evernote Tags catalog preset and see if the problem goes away. That will at least confirm that it’s not a coincidence.

**Comment by pjrobertson** [comment]
Hi @VBoudry 

It's been a while since we've heard from you, so I'm going to close this due to inactivity. If you're still facing an issue with the latest version of Quicksilver, please create a new issue.

Thanks!
