### ISSUE TITLE
iTunes plugin does not play iCloud tracks

### ISSUE THREAD

**Issue by calebbarr** [quicksilver/Quicksilver#2058]
When a track stored on iCloud is selected through iTunes > Browse Tracks, Quicksilver creates an empty playlist titled "Quicksilver" and does not play the track.  This issue does not present when a playlist is selected, even when the playlist starts with an iCloud track.  The iTunes plugin version is 2.6.0.

**Comment by skurfer** [comment]
Can you clarify “stored on iCloud”? Is it an “iTunes in the Cloud” purchase that hasn’t been downloaded, or something that shows up via iTunes Match? (They might have the same properties. I’ve never enabled Match because I’m afraid of what it will do to my library, so I haven’t been able to play with it.)

I can’t say exactly what’s happening here, but I’ll throw some facts at you and maybe you can figure out what’s going on.

  1. In order to play a track or add it to a playlist, you need to to pass its “location”. Only tracks stored on your local disk have a location set in the library, so only those are really useful.
  2. This is a known issue, and the plug-in should ignore anything without a location so I’m not sure how you can even *see* these tracks in Quicksilver. Can you find one of them in `~/Music/iTunes/iTunes Music Library.xml` and see if it has a location? If so, what does it say?

**Comment by skurfer** [comment]
This was fixed in version 3.0.0 of the iTunes plug-in.
