### ISSUE TITLE
Droplets fail to run

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2060]
If you drop something on a Droplet app, you get an error like this:

```
2015/05/27 1:41:42.290 PM QSDroplet[32123]: [NOTE: this exception originated in the server.]
[NOTE: this exception originated in the server.]
*** Object does not implement or has different method signature for selector 'isTransient’
```

Related to pasteboard changes?

**Comment by tiennou** [comment]
Doesn't even come near the amount of befuddlement I'm currently experiencing. Our NSPasteboard category isn't *loaded* (a.k.a a respondsTo quick test gets me `NO`).

This code path hasn't changed since either "code cleanup", or 2012 when I added `isTransient`, so it really looks like a genuine OS bug atm... I can just see the pasteboard comes from NSConnection, so maybe there's something caused by the IPC that causes the pasteboard to be one from whatever called us instead of our own "class" but still.

I am not amused ;-).

**Comment by tiennou** [comment]
(Note that a brand new NSPasteboard from inside our process responds to `isTransient` so it really seems an IPC glitch or whatever).

**Comment by tiennou** [comment]
Actually, this is no glitch. It just dawned on me that we're just in the presence of a DO proxy, so anything message we send it gets packaged and sent through IPC.

Which means droplets are broken since 2012 :-S.
