### ISSUE TITLE
1Password passwords not copied in clipboard plugin when retrieved 1Password mini

### ISSUE THREAD

**Issue by dmorel** [quicksilver/Quicksilver#2084]
To get a password, going to menu bar, click 1 password, enter first letters of searched login, select it and press enter or click on 'copy' on the password line; password is copied in pasteboard (using Cmd-V works) but doesn't appear in clipboard history content (not captured); it used to be "unknown clipboard object", but worked; now it's just not there anymore

**Comment by skurfer** [comment]
That seems preferable to the old behavior. “Unknown Clipboard Object” wasn’t very helpful.

You said you can still paste the password (until it expires, presumably), so is there anything that’s actually not working?

**Comment by dmorel** [comment]
Le 6 août 2015 2:58 PM, "Rob McBroom" <notifications@github.com> a écrit :
>
> That seems preferable to the old behavior. “Unknown Clipboard Object”
wasn’t very helpful.

That's what it said, yet when selecting it it was pasted normally. Or was I
drunk? :-)

> You said you can still paste the password (until it expires, presumably),
so is there anything that’s actually not working?

It's not kept in the history, so not selectable and so, not reusable as
soon as it's replaced in the system clipboard.

**Comment by skurfer** [comment]
> yet when selecting it it was pasted normally

Oh, that’s possible. It never occurred to me to go to the history for the top item when ⌘V would work.

> It's not kept in the history, so not selectable and so, not reusable as soon as it's replaced in the system clipboard.

It’s not supposed to be in the history at all. At least not with default settings. Do you have 1Password ignored by Quicksilver under Preferences → Clipboard? Do you have 1Password clearing the clipboard after 90 seconds or something like that?

**Comment by dmorel** [comment]
On 6 Aug 2015, at 19:41, Rob McBroom wrote:

>> yet when selecting it it was pasted normally
>
> Oh, that’s possible. It never occurred to me to go to the history 
> for the top item when ⌘V would work.

that's not what I said, I really think I could access it in the list of 
previous items

>> It's not kept in the history, so not selectable and so, not reusable 
>> as soon as it's replaced in the system clipboard.
>
> It’s not supposed to be in the history at all. At least not with 
> default settings. Do you have 1Password ignored by Quicksilver under 
> Preferences → Clipboard? Do you have 1Password clearing the 
> clipboard after 90 seconds or something like that?

None of these, I checked the app's (both QS and 1P) preferences before 
posting :)

**Comment by pjrobertson** [comment]
Well, actually you are right.

QS was changed (almost 2 years ago now) to respect other app’s preferences for not letting clipboard managers copy the data.
With Quicksilver we have adopted the standardised system for letting apps tell us whether or not to ignore data. Since 1Pwd chose to implement this as well, 1Pwd items won’t show in your Quicksilver clipboard.
See https://discussions.agilebits.com/discussion/comment/80412/#Comment_80412 <https://discussions.agilebits.com/discussion/comment/80412/#Comment_80412>

Now we could have an option to disable this (with a big security warning), but that would need you to create an issue at https://github.com/quicksilver/Quicksilver/issues/ <https://github.com/quicksilver/Quicksilver/issues/> outlining this, so that we can keep track of it.


I prefer to use encrypted email. You can find my public key here <http://patjack.uk/pk.asc>.
Learn how to encrypt your email with the Email Self Defense Guide <https://emailselfdefense.fsf.org/en/>
