### ISSUE TITLE
iTerm2 Plugin Fails to Run in iTerm?

### ISSUE THREAD

**Issue by timvisher** [quicksilver/Quicksilver#2086]
When trying to run `Run a Text Command in iTerm`, nothing happens and [this gets spit out in the logs](https://gist.github.com/timvisher/5a8525999ac655a44eeb).

Is this the appropriate place to log this issue. Anything I can do to help fix it?

I'm on iTerm2 Build 2.9.20150810-nightly.

**Comment by skurfer** [comment]
Probably the same thing described in quicksilver/iTerm2-qsplugin#5

> Is this the appropriate place to log this issue.

Yes.

> Anything I can do to help fix it?

Feel like updating the AppleScript in the plug-in?

**Comment by jasmas** [comment]
I started work on this, but actually started to refactor as a new plugin called iTerm3 because 2.9 will release as iTerm3 when stable. I'm not sure if some detection code would be possible or better. The bundle identifier will likely change when it releases as stable and detection would be easier at that point. I really just focused on fixing what was keeping it from compiling and getting the 'Run text command.." actions to work right. I think all the actions with named sessions are mostly useless now and that part probably still needs to be redone for profiles instead of sessions.

https://github.com/jasmas/iTerm2-qsplugin/tree/iTerm3

**Comment by pjrobertson** [comment]
Great, thanks! Probably keeping it as 1 plugin would be best if possible. Plugins can be related to multiple bundles - you're right a change in bundle ID would make things easier.

I've just gone through a similar thing for Safari 7/8 changes in the [Safari plugin](https://github.com/quicksilver/com.apple.Safari-qsplugin/pull/9/files#diff-f5b89cedda1bce5e23b2e108540b0304R318)
To check Safari version I'm checking for the existence of a file that Safari 8 creates. It's more complicated in terms of actions though.

If you feel like it should be a new plugin then we can also include that - when you're ready/iTerm3 is ready please make a PR or let us know on the [QS Dev group](https://www.google.co.uk/search?q=quicksilver---development) and we'll get a release out.

**Comment by studgeek** [comment]
I wrote this simple Pane 2 AppleScript Action to fill the gap in the meantime. Just drop it in `~/Library/Application Support/Quicksilver/Actions` and restart Quicksilver. Then it will show up as an available action for folders. Unfortunately it will also show up for files because I don't know the QS Type for just Folders.

```
using terms from application "Quicksilver"
	on get direct types
		-- TODO: Change to be just the QS Folder type (not sure what its name is)
		return {"NSFilenamesPboardType"}
	end get direct types
	
	on open files theFiles
		set filePath to POSIX path of item 1 of theFiles
		
		tell application "iTerm"
			activate
			set newWindow to (create window with default profile)
			tell current session of newWindow
				write text ("cd '" & filePath & "'")
			end tell
		end tell
		
	end open files
end using terms from
```

**Comment by studgeek** [comment]
Kind of obvious, but here is the script I am using to replace Run in iTerm3 until this is fixed...

```
using terms from application "Quicksilver"
	on get direct types
		-- TODO: Is there a File QS type that doesn't include directories?
		return {"NSFilenamesPboardType"}
	end get direct types
	
	on open files theFiles
		-- TODO: Handle multiple files
		set filePath to POSIX path of item 1 of theFiles
		
		tell application "iTerm"
			activate
			set newWindow to (create window with default profile)
			tell current session of newWindow
				write text (filePath)
			end tell
		end tell
		
	end open files
end using terms from
```

**Comment by studgeek** [comment]
For parent directory you just want to replace the `write text` argument with something like this:
```
"cd `dirname`" & filePath & "`"
```

**Comment by fturcheti** [comment]
Thank you for the scripts @studgeek!

**Comment by franvillamil** [comment]
A bit late on this, but @studgeek 's script is giving me the following error on Script Editor, and it doesn't run on Quicksilver:

```Expected function name, command name or function name but found “get”.```
