### ISSUE TITLE
Contact permissions being asked every time

### ISSUE THREAD

**Issue by elmart** [quicksilver/Quicksilver#2124]
Hi, 

Since I've upgraded to OSX El Capitan, QuickSilver asks for Contact permissions every time application is launched. Is this expected behaviour? Isn't there a way to permanently authorise QuickSilver to access Contacts? I've tried to manually set permission for QuickSilver in Privacy tab of System Preferences, but behaviour remains the same.

**Comment by skurfer** [comment]
It should only ask once, unless Gatekeeper fails to verify it (either because the application was tampered with, or it was signed by a different developer).

Are you running the official build from qsapp.com? Have you modified it in any way ([as described here][1], for instance).

[1]: https://github.com/quicksilver/Quicksilver/issues/2114#issuecomment-147214081

**Comment by elmart** [comment]
Ye!, I did the exact change you mention.
I'm not acquainted with GateKeeper issues. How should I proceed now, then?

**Comment by skurfer** [comment]
Assuming you have now installed all the plug-ins you care about, you can just go back to using the official copy. We should have a fix out soon, but you’ll need to go get it manually. We’ll announce it everywhere when the time comes.

**Comment by skurfer** [comment]
1.3.2 is now available. You’ll need to download and install it manually, as 1.3.1 us unable to connect and realize there’s an update.

http://qsapp.com/download.php

**Comment by elmart** [comment]
Ok, thx very much.
