### ISSUE TITLE
Changing monitors makes window appear out of the screen

### ISSUE THREAD

**Issue by juanfal** [quicksilver/Quicksilver#2182]
Changing monitors makes window appear out of the screen. Even if quit it, and restart, it still although less, has the top bar with the zoom, etc, buttons out of reach.

**Comment by skurfer** [comment]
Which interface are you using? (You can find out under Preferences → Appearance)

**Comment by juanfal** [comment]
Hi, 

Bisel (included), with Superfluous visual effects ON

**Comment by skurfer** [comment]
That one should center itself every time it becomes visible. Can you describe what you mean by “changing monitors”? I have an external display at work, but moving the focus to that one and calling up Bezel shows it right in the center.

**Comment by juanfal** [comment]
Well, that's exactly my situation. At work I have I fairly wide (ultra-wide, in fact) monitor.  But if it happens I open Quicksilver on that big monitor, then, like right now, opening it on the MacBookPro retina13, meshes totally its position.  It is impossible to handle and even if you close/open QS it, stills is wrongly placed.

Sending a partial screen capture.
<img width="924" alt="captura de pantalla 2016-02-03 a las 19 27 11" src="https://cloud.githubusercontent.com/assets/895596/12792526/8a3e57e0-caac-11e5-8b97-0da43430abea.png">

**Comment by juanfal** [comment]
Well, just now, after quitting/restarting it has centered it, not in previous experiences… But the problem is of course, as I have sent you in the screenshot, still there.

**Comment by skurfer** [comment]
Oh, you’re talking about the Preferences window. I was only looking at the actual Quicksilver interface.

It seems to remember the screen and position every time I open it, so it’s never in the “wrong” place. Does this only happen if you open it and make it large on the external display, then disconnect that display and try to open it again?

**Comment by juanfal** [comment]
Not exactly, in fact, I didn't change its size in the external display, as far as I can remember.  It happens always after opening on the external (laptop screen close) and _then_ on the laptop own screen (external disconnected).  The problem here is it takes negative Y coords for the window, so is impossible to access it

**Comment by tiennou** [comment]
I think you might be able to workaround the issue by Mission Controlling the preference window on another Space and back. Hopefully the window server will notice the weird coordinates and fix them by itself.

**Comment by juanfal** [comment]
I tried that, but it seems OSX knows it is not a normal window and doesn't allow you to assign it any Space but the main

**Comment by tiennou** [comment]
Well, you might be glad to hear I just reproduced it here ;-). I'll try to see if it can be fixed easily, sadly my second monitor is at work, and it seems quitting restores it correctly.

**Comment by tiennou** [comment]
@juanfal If you happen to have your external monitor handy (as I won't come near mine until Monday), can you try it again while running that [build](https://www.dropbox.com/s/o6uaet1vyy40gou/Quicksilver.app.zip?dl=0). You'll get signing errors because I can't sign so you might need to ⌃clic > Open to bypass GateKeeper but otherwise it's straight out of #2183.

I think the reproduction steps for your issue are :
1) open preference window
2) disconnect monitor.

Maybe 1.5) arrange the pref window to be flushed against the top of the external, just to make sure the coordinates will be off when windows will be rearranged at 2).

**Comment by juanfal** [comment]
Oh, sorry, same situation right now, tomorrow I'll try, I hope!

**Comment by juanfal** [comment]
Ok! you have made it.  Tried it and it works.  Just after opening it in my external monitor, I've opened it in the laptop and I saw how it repositioned itself moving the upper part of the preference window inside the screen frame.  Thanks!!!

**Comment by cro** [comment]
I know this issue is closed, but I have noticed a repeat of this behavior since I got new monitors at work.  I have 2 2560x1440 monitors and I also use my MBP's display (total 3 displays).  I've noticed that it is possible to move the QS interface to a place that will make it pop up totally off-screen if I switch to a set of displays with lower resolution.  I can fix it by switching interfaces from Primer to Bezel and back, but it would be nice if that wasn't necessary.

**Comment by tiennou** [comment]
@cro This issue was about the preference window, not the main interface. I'd appreciate it if you opened a new issue for that, and provided a little more information, as I haven't been able to reproduce using one external Apple Thunderbolt Display, set as my main display.

Things I've tried, with Primer :
- drag the interface to the bottom right corner of the main display, check that it opens here each time, close iface, disconnect monitor, invoke QS. Interface is flush against the left side, but appears in its entirety.
- drag the interface to the center of my laptop's screen, close iface, disconnect, invoke. Interface shows up as above.

What do you mean by "switch to a set of displays with lower resolution" ? Resolution change vs. monitor disconnection ?
