### ISSUE TITLE
Full Text Crashing

### ISSUE THREAD

**Issue by AceAttorneyMaster111** [quicksilver/Quicksilver#2192]
In the QS main command window, I frequently press the <kbd>.</kbd> key to enter more detailed text, usually a Bash command, in the text box. At about a 50% rate, and never immediately after I open the app, this causes QS to crash and forcequit. Upon reopening, it works perfectly one time and then, as I said, about a 50% chance of it working. For the record, I almost always open the QS command window with a QS-defined shortcut, <kbd>⌘</kbd><kbd>⌥</kbd><kbd>⌃</kbd><kbd>⇧</kbd><kbd>fn</kbd><kbd>F4</kbd>. I use OS X.11.4.

<a href="http://pastebin.com/g9HddQYz">Here</a> is a pastebin of the crash data. Thank you!

**Comment by skurfer** [comment]
It looks like you’re running Quicksilver 1.3.2. That crash was fixed in 1.3.3 (which is not even the current version).

There was a change in OS X that broke the update system in Quicksilver, which is probably why you didn’t see the new version. We’ve fixed that, but you’ll need to grab and install the latest version manually. You can get it from https://qsapp.com/download.php
