### ISSUE TITLE
Add documentation directory and require updated docs with pull requests?

### ISSUE THREAD

**Issue by gavinhughes** [quicksilver/Quicksilver#2200]
In general, Quicksilver needs better documentation. Adding a documentation folder to the GitHub repo and requiring updated docs for all pull requests that add/change/remove features would be very useful for existing and new users.

Is this something the developer community would be willing to support?

**Comment by skurfer** [comment]
Do you mean documentation for developers or users?

We’re pretty good about capturing both in the change log. I’m against having people update that file in their pull requests because they’d almost definitely be updating the same line, which would mean every single one would cause a merge conflict.

I think the main problem is for a new developer trying to come in and figure out what’s going on. For this, we now have “The Map” in the project’s root directory, and we’re trying to add Doxygen comments as we make changes, though it isn’t strictly enforced.

**Comment by gavinhughes** [comment]
I mean for users.  Take the new collections functionality introduced in 1.4.1. Is this added to documentation anywhere other than the changelog?  If only in the changelog, this then requires new users to parse the changelog from beginning to end to discover this functionality.  Not very friendly.

**Comment by skurfer** [comment]
> I mean for users. Take the new collections functionality introduced in 1.4.1. Is this added to documentation anywhere other than the changeling?

The new (and some old) keystrokes were added to the Quick Reference, but there’s no mention of anything new in the manual. If the manual is what you’re referring to, there’s no question it needs to be updated, but I don’t know if having developers do that via Git is a workable system.

Do you have any examples of other projects doing something like that we could look at?

> If only in the changelog, this then requires new users to parse the changelog from beginning to end to discover this functionality. Not very friendly.

Maybe it’s not ideal, but you don’t need to read it all. The current release is always on top. And that seems _much_ friendlier than trying to locate the one new section in an otherwise unchanged 125 page manual.

**Comment by gavinhughes** [comment]
How about using a [GitHub wiki](https://github.com/showcases/projects-with-great-wikis)?  If developers don't want to do it, other users could, including me.  We could migrate the entire manual to it. To keep current, make a simple checklist. Add items to the checklist based on the changelog for new versions.  The items is checked off when the wiki is updated.

**Comment by skurfer** [comment]
> How about using a GitHub wiki?

I would completely be on board. We should hear from @hmelman and @pjrobertson on this topic, though.

**Comment by hmelman** [comment]
I ok, I think I'm onboard with this. I'd upload the latest version I have of the manual to the wiki and work with others to bring it up to date.

**Comment by skurfer** [comment]
Great! I’ve re-enabled the wiki and added both of you as collaborators. I think that should let you edit it.

The access controls don’t appear to be great. It looks like we can either give certain people access to everything in the repo, to allow anyone on GitHub to edit the wiki. It’s an experiment. We’ll see how it goes. Let me know if you have any trouble.

**Comment by hmelman** [comment]
Ok, so what's the plan for this? (Still a GitHub novice here). Will the QS wiki live on GitHub (under the wiki tab) or is this source that will be installed on qsapp.com? Do I have to edit on GitHub or can I edit local files and push the text to GitHub?

What format should we use? The GitHub wiki supports several including Markdown and MediaWiki. Unfortunately they don't support MediaWiki table of contents which would be nice. I hope whatever we use it supports key symbols like the command key: ⌘.

My idea was to take the current manual and upload it, with wiki pages mapping to the existing sections of the manual. I can get the text up and I'll make the links between pages work. In the text, action names are bolded, I'd have to do that by hand and might leave that for after (with a team of editors helping?). Ideally we'd have some indexing mechanism so that we can make an index of actions. Indexes for Plugins and proxies would also be great. Not sure if any wiki format supports that cleanly. Categories (are they supported?) for plugin pages would be fine, but they won't work for actions since a page/action seems excessive. 

I won't upload images, I feel most all need to be updated and that would be a really great thing to divide up among a team of editors.

**Comment by gavinhughes** [comment]
> My idea was to take the current manual and upload it, with wiki pages mapping to the existing sections of the manual. I can get the text up and I'll make the links between pages work.

Good idea.

I'll work on migrating/updating text from the manual to the wiki, and also adding updated images.

**Comment by skurfer** [comment]
I’ve never used the wiki feature either. It’s possible it won’t work for us, but like I said, it’s an experiment.

Some quick points before things move too far:

1. I’m referring to the Wiki tab at the top of this page. That’s where the manual should end up.
2. Markdown. Times a billion. 😃
3. Let’s try to structure it so the wiki could potentially be used for something other than just the manual some day (just in case).
4. As far as I can tell, it’s completely flat, which could make the previous point a challenge, but I’m sure we can manage.
5. I think you can edit through the web interface, or clone the wiki as a Git repo itself. I’ve never tried either.

Getting the text out there sounds like a good start. I can help grab images as well. Could we come up some convention for marking missing images in the text so they're easy to find? Like "NEED_IMAGE description of image" or something?

**Comment by hmelman** [comment]
Ok, I filled in Part 1. Let me know what you think before I do more.

- I'm using **_this_** to show terms being introduced. There's no underline to use
- I'm using `this` to show things you type. I'm torn about using it for symbols like `←` and have used both. Let me know what you like. I think I like `←` but it's a lot more manual work to do.
- Tables are working ok and symbols like ⌘ seem to work fine (I'm only testing on safari on a mac, I assume mac only is ok for QS).
- I used indented code for some examples, but I can't use formatting in there. E.g., in the Concepts page I couldn't bold the actions in the indented example commands.
- I'm not marking where the images are, I think the best way is for someone to look at the pdf manual and figure it out.
- There are some parts in the text marked TODO, this means the writing needs to be updated.

**Comment by tiennou** [comment]
I like that project !

- Purists consider underline to be "visual", Markdown only knows about *emphasis* ;-)
- I'd go toward → instead of `→`.
- I think that it should be cross-browser, and depends on the reader having a Unicode font that provides those characters — for the lore, ⌘ is U+2318 — PLACE OF INTEREST SIGN 👀.
- Yep, indented code blocks are exempt from styling.

Would it be acceptable to build our own Jekyll-something that we could host on qsapp.com instead ? I think that styling things nicely in the Wiki is gonna be hard... Or [this](http://stackoverflow.com/questions/2606606/jekyll-documentation-to-pdf-with-toc) 😉.

**Comment by gavinhughes** [comment]
@tiennou Agreed on all points.  Jekyll would be much better for styling, but requires more commitment to build and maintain.  Is there a middle ground with lower overhead and more styling flexibility?  I would definitely be onboard with Jekyll if that's where the community wants to go.  I proposed the GitHub Wiki because it's the simplest possible solution.

**Comment by hmelman** [comment]
Haven't used Jekyll before but looking at the site I'm not sure what it buys us. Unless you propose adding our own markup tags, but I'm not sure it's worth it. If we really wanted that, we could just use html span and css classes for action, keystroke, etc. Generating a TOC isn't really needed. Indexes would be nice but I don't see that Jekyll does that out of the box. Moving to a wiki is a good thing, but I don't think there needs to be a pdf build of the manual anymore. If this is just to have a way to build a site with the manual to install someplace, I'm agnostic about that (particularly if it's using markdown syntax).

**Comment by skurfer** [comment]
At first glance, it looks great. I think this will be a lot more approachable than the PDF.

> I used indented code for some examples, but I can't use formatting in there. E.g., in the Concepts page I couldn't bold the actions in the indented example commands.

I was going to suggest using block quotes for that instead. It looks like you already did in at least one place.

> Haven't used Jekyll before but looking at the site I'm not sure what it buys us.

Agreed. I’d rather stay with the GitHub wiki. Something like Jekyll is fine for developers, but is that really what you want them spending time on? It also makes us a bottle-neck. The wiki makes it realistic for almost anyone in the community to contribute.

**Comment by hmelman** [comment]
> > I used indented code for some examples, but I can't use formatting in there. E.g., in the Concepts page I couldn't bold the actions in the indented example commands.

> I was going to suggest using block quotes for that instead. It looks like you already did in at least one place.

On the Concepts page I have examples of both. I'm looking for consensus. I like the fixed width font of the code example but the bold of the blockquote. The manual doesn't have this style of commands all that much, so I could just avoid it and put the examples inline (or these are good place holders for images), but I think settling on a convention would help. Bolding actions, particularly in the sections on plugins makes them stand out a lot and helps scanning to find something you're looking for. Then again having a short hand to type a whole  command (object, action, argument) is useful too.

**Comment by gavinhughes** [comment]
I think numbering section heading, "III – Features", is not as good as simply "Features". This is minor, but it will inform how we move forward. I think the absolute minimum said and shown to convey information and guide the reader is preferable. For example, I think the entire "How to Read this Manual" section should be removed.  The manual itself should be a sufficient guide on how to read the manual. It should be obvious by looking at Home that new users need the installation section, experienced users wishing to extend Quicksilver need "Extending Quicksilver", etc.  I run the risk of stepping on toes here, but I think most people know what they need and want as few words as possible.  They just want the meat.

**Comment by hmelman** [comment]
Ok, I think I'm done. I've uploaded all the text of the manual. Have at it :) I think it might be good to add a "status" at the top of each page and have people work on them one at a time. I think Part 1 is pretty up to date, Part II less so, and much of Part III is out of date.

@gavinhughes You may be right, particularly with the manual in wiki format. At the time there was a lot of quick How To Get Started with Quicksilver pages and videos on the web, I wanted something more comprehensive which didn't exist. As a 100 page PDF I felt I needed some brief explanation for new users to not overwhelm them. A big problem in figuring out how to write a manual for Quicksilver was figuring out how to organize it (particularly for print). I didn't want to repeat stuff like how to make a trigger or use the comma trick all over the place but I also didn't want to burden a new user with a ton of Configuration stuff up front before they could do anything useful. My solution was the Concepts and Configuration parts followed by all the plugins grouped by function. This didn't seem like an obvious structure to others so I explained it briefly at the top.

**Comment by hmelman** [comment]
There's a few places in the manual where other sections are referenced that aren't the top of a page, e.g., The Comma Trick. I didn't make them links, I just wanted to get all the info down. My first thought would be to make them named anchors in the page and then create links to those anchors. Another way would be to break stuff out into smaller pages, so there could be a Comma Trick page. My preference is for the first way (info stays together, people have less clicking to do to read things, the toc and sidebar stay shorter) but the second might be good (it's more wiki-like, there's no need to use html syntax in the pages, etc.). Thoughts?

**Comment by gavinhughes** [comment]
@hmelman I just removed "How to Read..." and most of the installation page. To me, far fewer words makes Quicksilver more approachable to new users, which is the focus of these sections. All the directory structure stuff and other details can be placed elsewhere.

My changes can be reverted if this view is not shared. I'm still experimenting to reach a consensus on how to proceed.

**Comment by pjrobertson** [comment]
Sorry I haven't chimed in on this. I like the idea of this Wiki, and nice work everyone/thanks for updating it!

One thing I've never liked about the GH wiki is the lack of hierarchy on this wiki. Reading [this](https://stackoverflow.com/questions/11088285/github-wiki-directories) SO thread it seems like a good idea is to use namespacing. So perhaps you guys can change the names of the files already created to prefix them with something like 'guide'. E.g. 'guide-installation' and 'guide-triggers'

This would also solve Rob's point:

> Let’s try to structure it so the wiki could potentially be used for something other than just the manual some day (just in case).

If we can move all the info over from the existing (old) wiki then definitely let's do that and then we can close the old wiki down. We'd then just need an organised way for letting people know how to contribute. I see the wiki has the ability to use header/footer files so we can add a header along the lines of "Want to contribute to the wiki? Then do x, y and z"

**Comment by hmelman** [comment]
@gavinhughes While I know I can be wordy and much of the manual needs editing, I think it's a mistake to remove "most of" a page saying the "other details can be placed elsewhere" _without actually placing them anywhere_. To me, basically what you did was delete a lot of info before reaching any consensus. What does anyone else think?

@pjrobertson Apparently that thread says they added support for directories but all page names still need to be unique. I'm not sure if names can have spaces in them, so I used hyphens. I also learned that one word pages can be referenced simply as `[[Page]]` which was convenient. Given the number of pages we have now I think we're ok (the sidebar seems the right length to me). If we think we'll be adding lots more pages, that might change. I agree with Rob's point too, but I'm not sure how to do that without knowing the uses. The obvious thing is breaking out the plugins to have their own pages, I've already given my thoughts on that. Others?

I took a quick look at the old wiki and there's more there than I thought. The approach I'd take is to delete stuff from the old wiki as it's moved to the new (I'd do that with the FAQ). That way the old wiki itself works as todo list. Thoughts?

**Comment by skurfer** [comment]
> What does anyone else think?

I didn’t get a chance to read it fully, but I felt like the “How to Read This Manual” page was worth having. As for the installation page, I’d have to see what was changed, which I don’t have time to look at until later.

On the other stuff, I don’t know if it’s time to dive in and replace the existing wiki based on the limited experience we have so far. I do love the idea of being able to use Markdown and not having to maintain a MediaWiki install, but I think we should let this trial run a bit longer.

**Comment by skurfer** [comment]
OK, I’ve looked things over.

* I prefer the look without the part numbers
* I think the How to Read This Manual page is helpful and not very long
* I agree with removing the list of files from the Installation section, but it should be available in the Appendix somewhere

I restored the “How to Read…” page, but as Howard pointed out in a commit, there are references to part numbers in there so I updated it to use the names of the sections as they appear in the table of contents instead. (Anyone working on the wiki should probably skim recent commits, or at least the log for the file they’re about to change, to see if there’s a reason for it being the way it is.)

There may be other references to part numbers we need to clean up, but… add it to the list of clean-up tasks. 😃

**Comment by hmelman** [comment]
Fair enough. I'm good with most of that. I'm not good with removing info to be put someplace else later. Moving needs both, otherwise it's deletion and is likely to get lost. 

I'm probably too close to this. I read the details in the Installation section and remember all the user questions at the time that led me to writing this stuff down some place.

**Comment by gavinhughes** [comment]
Ok, so more detail, not less.  I was just proposing a very terse style knowing that it could be easily reverted. Placing the removed content would have been the next step if terse was acceptable. The wiki is not like git where a complete changes can be pushed all at once.

**Comment by skurfer** [comment]
> The wiki is not like git where a complete changes can be pushed all at once.

They can if you clone the wiki locally and work from there. That’s what I’ve been doing. Much nicer, and related changes can be kept together.

**Comment by hmelman** [comment]
I'm fine with terser. Lists instead of prose is probably better on wiki vs pdf. The original point of this document was to be comprehensive because there was nothing else that was. I tried to put the important stuff at the top of each section and the less important stuff at the bottom, hence the details about what gets installed where at the bottom of the Installation section. 

The reason the manual never reached a 1.0 was because I was still gathering complete info. It was always planned to have a big rewrite for style once all the info was gathered (I started removing references to "you"). I'd really much rather see edits to update the info to be accurate rather than style at this point, but I get that it's easy to make things more correct by removing stuff that isn't accurate.

When we get to the "Features", I consciously tried to write *all* the installation requirements of a plugin at the top of a section before describing the usage, because that was a source of a lot of user questions. Please try to continue this.

**Comment by skurfer** [comment]
Would you be willing to put together some kind of style guide on the wiki @hmelman? Not just for what should be bold, but also some discussion of rationale, history, things to watch out for, etc. Whatever you think people need to know when working on the manual.

I don’t want this issue to be the only place to find such information.

**Comment by hmelman** [comment]
Done, in the appendix. There are a couple of TODO questions in there we should reach consensus on.

**Comment by skurfer** [comment]
The guide looks great. Thanks!

For keystrokes, it’s a bit of work, but probably worth it to just use the `<kbd>` tag. For example:

<kbd>⌘</kbd><kbd>Space</kbd>

If you have all the wiki files checked out locally, you can use your favorite editor to make it a bit easier.

For images, I looked at some of the examples in GitHub’s showcase. It looks like we can create a folder for them and just link to them using the Markdown syntax. Creating the folder and adding the images might only be possible via the filesystem. I’ve added one to the main page as an example. I couldn’t use a relative URL for some reason, but maybe we can figure that out. I think we can control the size and maybe placement, too. The other examples are probably the best place to check.

**Comment by hmelman** [comment]
I changed the Concepts page to use `<kbd>`. I ended up grouping keys together, such as:  <kbd>⌘;</kbd>, <kbd>⌥⌘S</kbd> rather than separate ( <kbd>⌘</kbd><kbd>;</kbd>). It looks better in some cases,  <kbd>Desk</kbd>, but I like your example better, <kbd>⌘</kbd><kbd>space</kbd>. Maybe <kbd>space</kbd> and <kbd>return</kbd> should be shown that way but others not? Thoughts?

**Comment by hmelman** [comment]
Question: to work on the wiki locally, I see the clone url to use but...
- Should I fork the GitHub repository or not (my guess is no)
- I should work on branches locally shouldn't I? (my guess is yes)
- And then I merge changes to master and just push them? I think that's right (or what the GitHub help suggests) but shouldn't there be pull requests involved?

**Comment by skurfer** [comment]
Since the style mimics physical keys, I feel like the manual should use it for anything that lives on its own key, but I can live combining some if you disagree. I’ll volunteer to add the `<kbd>` tags to all the existing text.

From what I can see, the wiki has a repository, but none of the usual GitHub stuff is attached to it. So I don’t know if you even _can_ fork it or do pull requests.

Since you have push access to the real thing, I’d say don’t fork. I would create branches if you’re doing anything major that you’re not sure about. If there are no pull requests, as I suspect, you’ll just need to send us a message and say “look this branch over”. I’ll look into it a bit, but for now, I’d say keep making changes using whatever means you’re comfortable with.

**Comment by hmelman** [comment]
I can agree to using `<kbd>` for individual keys. I think we should continue to use the Unicode symbol for the key, as shown in menus rather than what's printed on the key, so <kbd>^</kbd> not <kbd>ctl</kbd>. And if describing text to type that's separate keys for "Desk" as in typing "Desktop".

**Comment by hmelman** [comment]
I updated the Concepts and Terminology page as discussed.

**Comment by skurfer** [comment]
> I think we should continue to use the Unicode symbol for the key, as shown in menus rather than what's printed on the key, so <kbd>^</kbd> not <kbd>ctl</kbd>.

Agreed.

> And if describing text to type that's separate keys for "Desk" as in typing "Desktop”.

I’m not clear on which you’re arguing for between <kbd>desk</kbd> and <kbd>d</kbd><kbd>e</kbd><kbd>s</kbd><kbd>k</kbd>. I will say that when you used <kbd>Desk</kbd> as an example above, I thought “What’s the Desk key?” Maybe when it’s in context, it will be less confusing.

**Comment by skurfer** [comment]
> I updated the Concepts and Terminology page as discussed.

I looked it over and I see which you went with. I think it’s good. Maybe a bit noisy, but bold, italic, and quoted text are already being used in other ways, so I think it’s good for making it clear what’s being typed.

**Comment by hmelman** [comment]
I updated the Manual Style Guide page.

**Comment by hmelman** [comment]
Ok, please check the wiki git to make sure it's all fine. I added an image to images/ and included it in Concepts. It's my first git push. I just added it on my local master and committed it. Then did `git fetch` and `git merge` and ultimately `git push origin master`. I tried using Emacs' magit porcelain but found it confusing. Before the last step it showed my commit as "Unmerged to origin/master" which confused me (so I just did the `git push origin master` from the command line).

I know to use branches for bigger changes, but I just wanted to try adding an image and thought keeping it simple would be... you know, simpler. :)

**Comment by skurfer** [comment]
It all looks good to me. I usually do something like this (for simple changes with no branching).

1. Make the changes
2. `git add` any new or updated files
3. `git pull --rebase`
4. `git push origin master`

I’d like to start going through the manual and making notes about what needs to be updated. Do you think it’s too early for that?

**Comment by hmelman** [comment]
I'll keep that in mind. The rebase stuff is still alien to me.

Not too early at all. I think it all needs to be gone through. The Intro and Config sections are where terms are defined. We're probably fine, but it's worth a pass there so if there's something new (perhaps "collections" used for "the comma trick" or aliases?) it can be used in the Features section. Otherwise I'd go through the Features section by section making sure everything is covered (the hard part of this is finding out everything the plugins do, I used to go through the plists by hand).

I'd have a note at the top of each page stating how up-to-date it is. Another route would be an appendix page with a checklist of plugins.

**Comment by skurfer** [comment]
> Not too early at all. I think it all needs to be gone through.

OK.

> Otherwise I'd go through the Features section by section making sure everything is covered (the hard part of this is finding out everything the plugins do, I used to go through the plists by hand).

We’ve been pretty good about making sure plug-ins are fully documented over the past few years. At this point, I think it’s safe to let the built-in documentation be where we send people for details, but I do think it would be nice for users if we hit some of the highlights in the manual.

We just need to figure out how we’re going to refer people to the built-in documentation. Do we just tell them how to look at it in the app, or link them to the plug-in’s `Documentation.mdown` on GitHub (which is the source of the built-in docs)?

**Comment by hmelman** [comment]
If the GitHub wiki is to replace the qsapp.com one, then yes, I think the Guide preferences in the app should link directly to it.

I agree the the plugin documentation is now very good and I'd use that instead of diving into the plists. I think the plugin docs and the manual should serve a different purpose. The plugin docs are good for what they are, a description of the features the plugin adds. The Manual should introduce QS and all it's concepts and provide context for all the features and plugins. So obviously all the Configuration stuff should be in the manual. A plugin should describe any proxy object it adds, the manual should explain what a proxy object is. New users should be pointed to the manual. 

I think the manual's features structure allows plugins to be compared in a way the builtin docs don't. E.g., comparing the support of various browser plugins and how Mail plugins work similarly with the Email Support plugin and Contacts and files. The manual should be rich with example and "tricks" so people can get ideas of how to adapt QS to their use, that's not in the plugin docs either.

I'll do a pass today and remove the hyphens from the names of the wiki pages (I didn't realize names could have spaces). This makes the links to pages easier.

**Comment by hmelman** [comment]
I restored some stuff to the Installation section. It's been 3 weeks and the information wasn't put someplace else so prevent it from being lost, I put it back. It makes sense to me to be here because it describes what's installed and lists things to be removed during a complete uninstall. If people think it's better in an appendix, fine, but put it there, don't just remove it from here. I did add some styling to this page

**Comment by hmelman** [comment]
I've finished adding kbd tags to all the wiki pages.

**Comment by skurfer** [comment]
I started going through and making changes. If you’re not using a GUI Git client, `git log --oneline --decorate --color --graph` should give you a nice summary.

**Comment by pjrobertson** [comment]
I'm not sure when this happened, but the manual at [qsapp.com/manual](https://qsapp.com/manual/) is incredible!

Congratulations and great work to all those involved. Where are the original files stored, and is it editable e.g. via GitHub or a wiki?

I'm going to close this issue now, however please re-open if there are still some documentation parts missing. Thanks

**Comment by skurfer** [comment]
> Where are the original files stored, and is it editable e.g. via GitHub or a wiki?

@pjrobertson The files are at https://github.com/quicksilver/manual

**Comment by pjrobertson** [comment]
Noted, thanks. Beautifully clear README there! 👍

**Comment by hmelman** [comment]
It's basically all my original text with someone's (@skurfer's?) formatting.  It's still missing a ton of images from the pdf version of the manual, which I think would help a lot.

**Comment by pjrobertson** [comment]
Right. It still overwhelms me how much work you put into the original manual. It's a long shot, but do you have the original images still (in a folder somewhere) that you're willing to share? That would help a lot in getting them into the repo.

**Comment by hmelman** [comment]
I don't.  I think the best bet is to go through the original pdf and just generate new images based on what's there.  Basically it's just all the Preference screens, which have changed a little, and then a bunch of command windows.
