### ISSUE TITLE
Program crash immediately after reboot or restart of Quicksilver

### ISSUE THREAD

**Issue by yetiboy** [quicksilver/Quicksilver#2210]
Constant crashing since the last update.

Here are the logs from the last 24 hours:

[Archive.zip](https://github.com/quicksilver/Quicksilver/files/286953/Archive.zip)

**Comment by skurfer** [comment]
It looks like a problem reading the clipboard history. You could try clearing it out.

Delete `~/Library/Application Support/Quicksilver/Shelves/QSPasteboardHistory.qsshelf` and see if Quicksilver will launch.

Also, make sure you’re on the most recent version of the Clipboard plug-in. A very similar crash was fixed in 1.4.3. See quicksilver/elements.clipboard-qsplugin#16

**Comment by yetiboy** [comment]
Looks like one of the two suggestions worked - odd that Quicksilver said all plugins were up to date when the Clipboard plug-in was on version 1.4.2 instead of the current 1.4.4. Thanks for your help.
