### ISSUE TITLE
Script Proxy Object

### ISSUE THREAD

**Issue by 1-61803** [quicksilver/Quicksilver#2259]
For lack of a better name. I thought of it this way. You would add such a custom object which takes shell or applescript commands in a text field. Then when you select this custom object in the first pane, QS executes in the background `shell commands ⇥ Run Command in Shell` or `applescript commands ⇥ Run as AppleScript` accordingly and returns, let's say, paths, which are automatically parsed — much like when you change the first pane to text mode and paste paths and tab to select a further action. I guess it would be like a `qscommand` that's run on selection. And whatever it returns it may or may not be parsed by QS.

[Forum thread](https://groups.google.com/forum/#!topic/blacktree-quicksilver/CIahwtlBtyA)

**Comment by hmelman** [comment]
> You would add such a custom object which takes shell or applescript commands in a text field. 

A text field where? Is this some configuration thing in the catalog? Where do you add an object? AFAIU that's unlike anything that exists.

> Then when you select this custom object in the first pane, QS executes in the background shell commands ⇥ Run Command in Shell or applescript commands ⇥ Run as AppleScript accordingly 

When you *select*? Proxies don't run when you select, they "run" when you hit Return and execute a command or if you right-arrow into them

> and returns, let's say, paths, 

What if it doesn't return a path? Say it returns an URL or something else?

> which are automatically parsed — much like when you change the first pane to text mode and paste paths and tab to select a further action. 

Ok, that's like something that exists.

> I guess it would be like a qscommand that's run on selection. And whatever it returns it may or may not be parsed by QS.

So why isn't this an action? Select your script in the first pane, and run an action like **Run and Parse Path** and then get a new command window with the output path parsed in the first pane (or some error handling happens). And then select a new action. If you want, make a trigger of this.

**Comment by 1-61803** [comment]
> A text field where? Is this some configuration thing in the catalog? Where do you add an object?

It could be in the catalogue via the plus sign at the bottom.

> When you select? Proxies don't run when you select

When I select Custom Web Page (Safari) there is some code that's fetching the URL, isn't it?

> What if it doesn't return a path? Say it returns an URL or something else?

URL's are parsed actually. Enter one in text mode and you'll see. As I clearly stated, may or may not be parsed.

> So why isn't this an action? Select your script in the first pane, and run an action like Run and Parse Path and then get a new command window with the output path parsed in the first pane (or some error handling happens). And then select a new action. If you want, make a trigger of this.

I'll answer that with another question — wouldn't it be useful to be able to customize an object with commands that list some specific recent documents or x last lines of a log in which you could right arrow and search for certain data?

It seems that you don't like this feature request. For the outline is quite clear.

**Comment by hmelman** [comment]
> > A text field where? Is this some configuration thing in the catalog? Where do you add an object?

> It could be in the catalogue via the plus sign at the bottom.

Ok, so this is less a proxy object and more likke a custom catalog source, much like a custom Web Search List, and you would add the script in the info pane of the source in the catalog (using the i button).

> > When you select? Proxies don't run when you select

> When I select Custom Web Page (Safari) there is some code that's fetching the URL, isn't it?

As I said, it doesn't run when you select it in the first pane, it runs after you hit Return, which means, critically,  it runs after you select an action. AFAIU with proxies now, you don't run them in the first pane to select what actions appear in the second pane, that's preconfigured.

> > What if it doesn't return a path? Say it returns an URL or something else?

> URL's are parsed actually. Enter one in text mode and you'll see. As I clearly stated, may or may not be parsed.

> > So why isn't this an action? Select your script in the first pane, and run an action like Run and Parse Path and then get a new command window with the output path parsed in the first pane (or some error handling happens). And then select a new action. If you want, make a trigger of this.

> I'll answer that with another question — wouldn't it be useful to be able to customize an object with commands that list some specific recent documents or x last lines of a log in which you could right arrow and search for certain data?

I suppose, but it would have been clearer if you just answered my question. A real use case, rather than a supposition would I think help me understand. My catalog already contains my recent documents and QS has some existing facilities to get at some others (e.g., right arrowing into an app). I haven't had the need to preconfigure a set of files in the catalog which seems like an extra step that's burdonsome enough I wouldn't use it. I'd rather just create a Finder folder with the files or aliases and bring that up in QS (no new features needed). Same with log files, I would just select the log in the first pane of QS.

My question was about the configuration step. Rather than do this in the catalog source info pane, it seems to me that if you could use QS's command interface it would be much easier to use and more flexible. Your "answer with a question" didn't address this.

> It seems that you don't like this feature request. For the outline is quite clear.

I don't like it or dislike, and it wasn't clear to me, that's why I asked questions and tried to describe it in terms that I understand to exist in QS.

And I just wrote a manual a number of years ago, it's up the developers to choose to implement this or not, not me.

**Comment by 1-61803** [comment]
As I said in the first post of the forum thread above referenced, [this problem](https://groups.google.com/forum/#!topic/blacktree-quicksilver/D8ZiqkzMWqg) made me think of this proxy (ie, I could the get right url via UI scripting).

And I still think of it as a proxy, acting as a command interpreter. Sort of.

Try selecting `Custom Web Page (Safari)` and changing to text mode - you'll see the url.

**Comment by skurfer** [comment]
> Proxies don't run when you select, they "run" when you hit Return and execute a command or if you right-arrow into them

Actually, right now it does both. (It has to resolve it as soon as it appears in the interface to get the icon, figure out what type it is, etc.) It also only remembers what it points to for a few seconds (so it won’t get stale), but that means it could point to something else by the time you “use” it. That’s something I fixed in #2179.

So the part about “running” something immediately is plausible, anyway.

Many of the use-cases put forward are either possible now in other ways, or as @hmelman said, sound more like catalog entries than proxy objects.

A couple of other thoughts on this:

  * If a proxy object is a good idea, it should just be added to one of the plug-ins as a proper proxy object.
  * You can already run AppleScripts and shell scripts that return results to Quicksilver, so I guess we’re just talking about saving keystrokes. So if you had an AppleScript called “Safari Address Bar” that got the text in the address bar no matter what, right now, you’d have to type `sab↩` to get the result. If it were auto-resolved, you could just type `sab`, saving a keystroke. But I would argue that you could just train QS to find it with `sb` instead, which would also save that single keystroke.

**Comment by 1-61803** [comment]
Then [#2259](https://github.com/quicksilver/Quicksilver/issues/2259) could be a particular case of [#2227](https://github.com/quicksilver/Quicksilver/issues/2227) for `shell commands ⇥ Run Command in Shell` or `applescript commands ⇥ Run as AppleScript`. I still think of it as proxy for an interpreter though. I wonder how you would save these objects in the UI.
