### ISSUE TITLE
unable to set default or decrease score

### ISSUE THREAD

**Issue by psifertex** [quicksilver/Quicksilver#2276]
Cannot change the results for any search as all options are disabled. Example image below.

<img width="366" alt="screen shot 2016-09-27 at 11 26 32 pm" src="https://cloud.githubusercontent.com/assets/140215/18899844/efaeb594-8509-11e6-821d-e17fce4dae60.png">

**Comment by skurfer** [comment]
Does this only happen *after* you dismiss the interface and call it back up?

**Comment by psifertex** [comment]
No -- here's a video showing me launching quicksilver, launching it for the first time and showing that behavior.

![quicksilver](https://cloud.githubusercontent.com/assets/140215/18917568/303d0622-8566-11e6-923d-fcf4d439e5cf.gif)

**Comment by skurfer** [comment]
Under Preferences → General → Command, do you have “Reset search after” enabled?

I can see that the text you typed isn’t appearing at the top of the results list, so it’s probably getting cleared before you can get down and right-click.

**Comment by psifertex** [comment]
Ahh, excellent -- that (mostly) fixes it, thanks. For the record, I don't remember enabling that, is it on by default? I still can't decrease the score of a result, but I can at least set a default which is good enough for now. Marking this as closed.

**Comment by skurfer** [comment]
I don’t believe it’s on by default. I also had it enabled, and I also turned it off as of 1.5.0.

Just so you know you’re not crazy, the behavior you saw is new. While working on the ability to remove just one character with ⌫, we discovered a bug where the search string wasn’t getting cleared visually when the search scope was reset. Now that it is, you lose the ability to “use” that string for things like the above.

Also note that 1.5.0 is more likely to need manual training because of a bug (since fixed) that prevented it from learning as you search.

**Comment by psifertex** [comment]
Thanks -- I was actually coming back to check for other bugs as I noticed that scores weren't increasing or decreasing based on choices I'd made and it sounds like you'd already caught that. 

I've got developer previews enabled and am checking for updates but don't see it live yet, checking for updates only shows 1.5.0. 

Is there not a live build process for more bleeding edge code?

**Comment by skurfer** [comment]
> Is there not a live build process for more bleeding edge code?

No automatic nightlies if that’s what you mean. You could always build a copy from the source, though. I’ll try to get a new release out soon.
