### ISSUE TITLE
drilling into folders with arrow or / no longer working

### ISSUE THREAD

**Issue by cdeliason** [quicksilver/Quicksilver#2281]
If I quicksilver a shortcut that brings up a folder, then hit right arrow or /, I should be able to then search using typing for a file within that folder. I'm finding now that once I begin typing, qs "forgets" that it's in the folder and gives me matches from the entire catalog. 
Not sure if this changed when I updated to Sierra, or when I updated to the latest quicksilver, but at any rate it has blown my workflow up! This is QS 1.4.2 (401A)

**Comment by skurfer** [comment]
Believe it or not, what you’re seeing was the default behavior for most of Quicksilver’s history. We changed it sometime recently, but you can still choose what happens when searching after →.

Right arrow into a folder, then select the gear menu at the top of the results list. (It probably says “Filter Catalog” next to it right now.) Go to Search Mode and choose “Filter Results”. You can also change the mode without the menu by hitting ⌘→ or ⌘←. (Hitting one of those accidentally is probably how you ended up with this problem.)

**Comment by cdeliason** [comment]
Thanks a million!
