### ISSUE TITLE
"current selection" proxy object not working anymore for text

### ISSUE THREAD

**Issue by Morriz** [quicksilver/Quicksilver#2285]
- type shortcut to start quicksilver
- select "current selection" in first pane
- select action in second pane, like "find with"
- apply web search object like Google (US)

nothing happens

"current selection" does not get populated somehow in any case

**Comment by skurfer** [comment]
Strange. In some apps, resolving Current Selection appears to steal focus from the previous application, which would help explain why the selection becomes empty, but that doesn’t always happen. I can get it to work with Large Type sometimes, but web searches aren’t working at all.

Thanks for the report.

**Comment by skurfer** [comment]
OK, when you select an action that uses the third pane (like “Find With…), the object in the first pane can affect what shows up in the third, so it tries to re-acquire the selection which fails because Quicksilver has focus by then. None of this behavior is new, so I have no idea why this wasn’t always broken.

This is actually fixed (unintentionally) by #2179, which resolves the proxy object once and keeps it until the interface is dismissed.

**Comment by hmelman** [comment]
FYI, that's never the way I invoke Current Selection, I always do it from a trigger (and almost always use Find With...) and I haven't seen an issue.

**Comment by skurfer** [comment]
That doesn’t surprise me, @hmelman. The problem happens when you select an action in the interface and the current selection gets resolved *again*. With your trigger, the action and indirect object (third pane) is already stored.

**Comment by skurfer** [comment]
This should be fixed in the next release.
