### ISSUE TITLE
Remove Evernote plugin from plugin download page

### ISSUE THREAD

**Issue by kejkoehler** [quicksilver/Quicksilver#2290]
Evernote Quicksilver plugin has been deprecated. It has not been actively developed since 2014. The plugin is causing severe performance issues with our latest Evernote clients and needs to be deprecated as soon as possible. Please respond to me with ETA.

Thank you,

Kathryn Koehler
Evernote Desktop Engineering Team Manager

**Comment by skurfer** [comment]
We can remove it, but there are a lot of people that would like to use that plug-in. Would your engineering team consider fixing it and submitting a pull request?

I’d be happy to answer any questions to speed up the fixes.

**Comment by kejkoehler** [comment]
We don't have plans to fix the plugin on our roadmap for at least the next
6 months. In light of that, please remove it for now and we will have it
reinstated once it is fixed. I apologize for the inconvenience and I
understand that people find it useful but we have higher priority items to
tackle at the moment.

-Kathryn

**Comment by skurfer** [comment]
It was removed earlier this morning.

**Comment by kejkoehler** [comment]
Thank you for your prompt turnaround. Do you have download stats on the
plugin? That will help me build the case to prioritize this work.

**Comment by skurfer** [comment]
Sorry, this slipped through the cracks.

I didn’t have an immediate answer because I just deleted the entry for Evernote from our database, and of course that’s where the download count was. I tried getting an old copy of the database going, but wasn’t successful.

Based on the total number of users, I would guess the number of people using the plug-in is around 40k. Probably not huge in Evernote terms, but I’m sure they’d appreciate any support you can offer.

**Comment by kejkoehler** [comment]
Thank you for the update.
