### ISSUE TITLE
Unable to overwrite files

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2297]
When moving/copying to a destination that exists, the conflict panel appears to ask the user what to do. If you choose “Replace”, from what I can tell, it will *never* work.

There’s code to delete the original before the move/copy, but it first [checks to see if the original is in the destination folder][1]. Well, how could it not be? Isn’t that the point?

Maybe I’m missing something.

[1]: https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSActionProvider_EmbeddedProviders.m#L669

**Comment by tiennou** [comment]
Moves are dangerous in this specific case : you move `~/Test` to `~`, and choose replace. [This](https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSActionProvider_EmbeddedProviders.m#L722) would have removed your original file, then the move/copy would fail because it was just deleted.

I've been wondering about how to fix it correctly, but went for the easy solution (which is keep it broken :wink:).

Here are the bunch of cases I can think of :
- you have `~/Test` and `~/Documents/Test`, and you move the 1st to `~/Documents`, you want to be asked about what should happen (eg. overwrite, abort, or "smart" in case Test is a directory).
- you have `~/Test`, and move it to `~`, then you want to throw an error because it's a nop (or a quick trip to your local backup, depending on whether there's a deletion involved).
- you gather a collection of files and want to move them in `~/Documents`. You'll have to check that none of them are already there, maybe allow the user to choose a "rename strategy" for those duplicates in the file conflict dialog.
- you gather a collection of files and want to move them in `~/Documents`. Some come from symlinked directories.

That's the point where I threw my hands in the air 😆.
