### ISSUE TITLE
Image Manipulation PlugIn BUG

### ISSUE THREAD

**Issue by Kethal** [quicksilver/Quicksilver#2300]
Dear Support, please note that after new update of QuickSilver I face a specific bug. Whenevery I make a screenshot via Image Manipulation PlugIn, the Quicksilver window remains on the screenshot (while in previous versions this Quicksilver window was hidden during screenshot snapping). See example attached
![screen region 2016-12-31 at 18 57 11](https://cloud.githubusercontent.com/assets/24855035/21578274/fbe6a1d4-cf8a-11e6-97f6-d1ef400ad6f3.png)

**Comment by pjrobertson** [comment]
Hi,

Please confirm:

* Your version of Quicksilver
* Your version of the image manipulation plugin
* Whether this happens for a different interface (e.g. the Bezel interface)

**Comment by Kethal** [comment]
Good day Sir
Happy New Year!

 Sorry for not providing versions beforehand:
- QuickSilver 1.5.1 (401C)
- Image Manipulation plugin 1.1.1 dated 31.01.14
- No i do not use any specific interface (only the default one)


BRGDS
Stanislav


2017-01-01 7:28 GMT+03:00 Patrick Robertson <notifications@github.com>:

> Hi,
>
> Please confirm:
>
> * Your version of Quicksilver
> * Your version of the image manipulation plugin
> * Whether this happens for a different interface (e.g. the Bezel interface)
>

**Comment by pjrobertson** [comment]
Thanks for the info.

I can confirm this is a bug with QS 1.5.1
@skurfer I’m running a `git bisect` now

**Comment by pjrobertson** [comment]
Seems the bad commit is 2b2cc2dfe4b7a3d4270581527d9ddd130bd8ce6f
@tiennou is the culprit!

Etienne - do you know what's going on here/any idea how to fix this?

**Comment by tiennou** [comment]
That's, well, convoluted. IIRC, what happens is that because of the clear-last-search changes (aeaa261352e3caa42838e3a1f4caa2a9ef90953c), the dSelector has no string, hence this (https://github.com/quicksilver/Quicksilver/commit/2b2cc2dfe4b7a3d4270581527d9ddd130bd8ce6f#diff-67e3a94a52a5e4a92915f1f10797045bL655) saves nothing, hence the mnemonics aren't updated.

*But* moving that `(!cont)` test makes the screenshot happen before we hide the main window, hence this bug 😠.

Maybe make the take screenshot action main-thread only ? That should queue the action in the next runloop instead of going through a background queue, which would allow the current runloop to complete and thus hide the window ?

**Comment by Kethal** [comment]
Dear Support,
Good day


 Any kind news regarding when will this issue be fixed?

 Pleased to hear, this function is so useful that I cant work without her
now :)


BRGDS
Stan

2017-01-09 16:55 GMT+03:00 Rob McBroom <notifications@github.com>:

**Comment by pjrobertson** [comment]
It's been fixed and will be out included in a new release soon. In the meantime you can downgrade to an earlier version of QS or wait it out for the new release!
