### ISSUE TITLE
Support cycling through application windows

### ISSUE THREAD

**Issue by dmocek** [quicksilver/Quicksilver#2305]
What I'm trying to do is have a keyboard shortcut which lets me:
- Raise an already running application to the foreground.
- If the application isn't running, run it.
- Once raised, continuing to hit the keyboard shortcut cycles through that application's windows.

Can this be done with Quicksilver?  I know I can raise/run with it and use Ctrl-~ to cycle through an application's window, but it requires me to use a shortcut to raise/run the app, then another to cycle through the windows.  I want a single shortcut to do both.

**Comment by skurfer** [comment]
Almost. You could create two triggers and set the scope for the one that launches/focuses the app to be disabled when that app has focus, then create another trigger with the same shortcut that cycles windows and scope it to only work in that app.

The problem is with the second trigger. The User Interface plug-in has ways to list, select, and activate windows, but I think for what you want, you would need a “Next Window” proxy object. There’s one for “Current Window”, but I don’t see one for Next. You might play with it and see if you can come up with anything that works well, but it might take some enhancements to the User Interface plug-in.
