### ISSUE TITLE
Quicksilver not responding in newly released 10.12.3

### ISSUE THREAD

**Issue by clarkn** [quicksilver/Quicksilver#2315]
After updating to Mac OS 10.12.3, Quicksilver 1.5.2 is not responding on boot. If I kill the process and restart, then it hangs on startup and consumes ~99% of CPU until I kill it.

**Comment by skurfer** [comment]
Hello. Can you [get a sample](https://support.omnigroup.com/sample-osx/) of the app when it hangs and share a link to it here?

**Comment by clarkn** [comment]
Sure. 
[Quicksilver Sample 2016-02-05-1524.txt](https://github.com/quicksilver/Quicksilver/files/753282/Quicksilver.Sample.2016-02-05-1524.txt)

**Comment by skurfer** [comment]
Give this test build a try and let me know if it’s any better. The version should show as “1.5.2:mine”.

https://cl.ly/0c3v0M031t3L

**Comment by clarkn** [comment]
It doesn't hang, but the process immediately exits. If I start in terminal with open, I get:

LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Quicksilver.app.

**Comment by skurfer** [comment]
Sorry. A debugging setting snuck into the release build. See if this is any better.

https://cl.ly/420r2R0z3R3d

**Comment by clarkn** [comment]
It crashed the first time I ran (and I sent the crash report) but then it started and seemed to be running ok. I killed it and when restarting it has returned to the original behavior of not responding. Sample below. 
[Quicksilver Sample 2017-02-07.txt](https://github.com/quicksilver/Quicksilver/files/758378/Quicksilver.Sample.2017-02-07.txt)

**Comment by clarkn** [comment]
Some other info in case it is helpful, if I delete/move ~/Library/Caches/Quicksilver. Then Quicksilver appears to start and work OK, but if I exit it and try to restart, then it hangs on startup again (unless I delete the caches folder again).

**Comment by skurfer** [comment]
That might be helpful. In the most recent report, it’s hanging during the initial launch process. It’s seeing if it needs to scan anything. Something is adding new objects to the catalog, and it’s making sure they aren’t duplicates.

With ever diminishing hope, here’s another build to try https://cl.ly/232C3L1k0p3d

FYI, the code that it’s getting stuck on always has something to do with looking up a UTI. I’ve been reducing or moving those calls, but they have to happen eventually, which is why I’m not sure this latest build will make any difference.

If you could, it might help to try and identify a specific catalog entry that causes this hang by disabling all of them and just testing a couple at a time.

**Comment by alexandertmills** [comment]
Were you able to resolve this? I'm using macOS 10.12.2 and I'm running into the same issue. QS has been working flawlessly for years on this machine, then suddenly just now it won't respond.

[Sample of Quicksilver.txt](https://github.com/quicksilver/Quicksilver/files/795391/Sample.of.Quicksilver.txt)

**Comment by skurfer** [comment]
That’s a very similar issue @alexandertmills but at a different point. (It’s loading previously scanned items from disk instead of scanning fresh.)

Here’s another test build to try: https://cl.ly/0N3W180S2G45

Whether that helps or not, could you try temporarily disabling catalog entries until you identify one or more that causes QS to hang? (You may need to go back to an older copy if that test build fixes the problem.) If you have time, I’d appreciate it.

**Comment by alexandertmills** [comment]
> could you try temporarily disabling catalog entries until you identify one or more that causes QS to hang?

Sure! How should I do that if it hangs at startup? I can't access the UI at all.

I'll give the test build a try tonight.

**Comment by skurfer** [comment]
> Sure! How should I do that if it hangs at startup?

Good point. Based on what I’ve seen, I think it will load if it scans fresh instead of reading from disk. So run this (in Terminal) before starting it up: `rm -r ~/Library/Caches/Quicksilver`

**Comment by alexandertmills** [comment]
Well, I got it to launch (and show the startup logo)! And then it froze again before I could access the preferences. :/

[Sample of Quicksilver.txt](https://github.com/quicksilver/Quicksilver/files/797687/Sample.of.Quicksilver.txt)

**Comment by lysiszegerman** [comment]
I had a similar issue with Quicksilver since a few days ago. Going through the catalogs it turned out that Safari history was 90k-100k items large. Disabling this catalog was reducing the startup time immensely. I didn't have this problem before and my Safari history haven't changed in a long time - was there maybe some change in the plugin that might've caused that?

**Comment by clarkn** [comment]
I forgot to update this thread. I did go through my catalog and it turned out that it was the plugin for my bash command history that was causing it to hang. It said it had 20k+ entries. I suppose this is because I disabled the max size on my bash history. When I disable this plugin, Quicksilver starts up normally. 

My command history has always been large and I don't recall any problem like this with Quicksilver before my update to 10.12.3.

**Comment by lazylady** [comment]
Same issue for me with Safari history above 150 000. Disabling Safari catalogue fixed it.

**Comment by skurfer** [comment]
> I didn't have this problem before and the size of my Safari history haven't changed in a long time - was there maybe some change in the plugin that might've caused that?

Yes, @lysiszegerman. Before the most recent Safari plug-in, history indexing was broken. So that entry went from 0 to 100,000 overnight.

@clarkn I can’t really reproduce that since my bash history only has 2 items, but I’ll see if the plug-in is doing anything obviously weird. Thanks for the update. (If there’s any way you could remove sensitive information and send my your history privately, that might help, but I understand if that’s not realistic or if you just don’t like the idea.)

**Comment by lysiszegerman** [comment]
@skurfer Ah, ok. Thanks for confirming, then this was the reason for the Quicksilver hangs on my end. It was occurring during start-up and when the laptop was waking up from sleep mode; not during normal operations though. Disabling the Safari history catalog is good enough for me right now.

**Comment by clarkn** [comment]
@skurfer I think I can live without the bash command plugin, but if you'd like to take a look at it, I emailed a sanitized history to your email listed on your profile.

**Comment by skurfer** [comment]
> I emailed a sanitized history

I got it, thanks. Unfortunately, it didn’t offer any clues. On my end, all the lines were quickly added to the catalog without incident.

**Comment by clarkn** [comment]
@skurfer 🤔 Are you on 10.12.3? I suppose my correlation with 10.12.3 and this bug may just be coincidence. 

Just to be sure it wasn't something specific to my unsantized bash history, I tried using the one I sent you and I have the same problem. I don't think I used the bash plugin very often, so it's not a great loss to have it disabled though I remain curious about the cause of the difference in behavior.

**Comment by skurfer** [comment]
> Are you on 10.12.3?

Yep.

> Just to be sure it wasn't something specific to my unsantized bash history, I tried using the one I sent you and I have the same problem. I don't think I used the bash plugin very often, so it's not a great loss to have it disabled though I remain curious about the cause of the difference in behavior.

Well, I think I was using a build basically identical to the one I sent you, but maybe not. I’ll try a few combinations and see if I can get it to hang.

**Comment by skurfer** [comment]
I was able to reproduce your problem, I think. It wasn’t actually hanging, just doing tons and tons of work. It eventually finishes and starts working. With your `.bash_history` in place, I got the launch time from around 35s down to around 5s (on my system).

I have a good feeling about this one: https://cl.ly/011O462y3r3C

**Comment by atlas5d-matt** [comment]
For what it's worth I was having a similar problem with the stock 1.5.2 build of Quicksilver on 10.12.3. I had both a 50k Safari history catalog and a 16k bash history catalog. If I disabled both of these the stock build started up fine for me. With @skurfer's latest test build I was able to turn on both of these catalogs and the app started up once more. With just the bash history enabled it anecdotally started up and became responsive about as fast as I'd expect, say a second or two. When I enabled the Safari history as well it took a few seconds, during which time the CPU load for the process was > 100%. After those few seconds though it was completely up and responsive and appeared to be working normally.

Here's a sample with both histories enabled: 
[Sample of Quicksilver.txt](https://github.com/quicksilver/Quicksilver/files/811714/Sample.of.Quicksilver.txt)

**Comment by skurfer** [comment]
Using the Bash history provided by @clarkn, I was able to find and fix a few issues. The time to launch Quicksilver with the current release was 5+ minutes (I didn’t wait for it to finish). I got it down to 4.5s. 😄 

Thanks everyone for the information and the patience. I’ll see what the other devs have to say about the changes, but if I don’t hear anything soon, I’ll put out a developer preview.

**Comment by clarkn** [comment]
@skurfer sorry it took so long to give it a try. The last version you posted above does start up ok with bash plugin enabled after a 4-5 second wait.

**Comment by TommyPec** [comment]
I have the same issue, both with 10.11.6 and 10.12.3.
QuickSilver starts to eat memory (it goes up to 10+ GB) and to read/write constantly on the disk.
The only solution is to kill it, but as soon as it is restarted, the problem starts again too.
I noticed more on the machine with 10.12.3, but it has also less RAM and a slower disk.

[Sampling.txt](https://github.com/quicksilver/Quicksilver/files/853713/Sampling.txt)
[OpenFiles.txt](https://github.com/quicksilver/Quicksilver/files/853714/OpenFiles.txt)

**Comment by skurfer** [comment]
1.5.3 is out as an official release now, and should address these delays.

**Comment by TommyPec** [comment]
If you look at the samples, these have been created by QuickSilver 1.5.3... the problem is still there (or maybe it's a different one).

**Comment by skurfer** [comment]
The sample above is from 1.5.2 and definitely related to the Safari History catalog preset. You could disable that if you don’t use it, but it really should be improved in 1.5.3. (In particular, the amount of time you need to wait after launching QS for the second time, when the catalog is loaded from disk instead of scanned fresh.)

**Comment by TommyPec** [comment]
Right, my bad. I did upgrade QS on one computer and not in the other one. Of course, I took the sample on the wrong one.
I disabled Safari History indexing and all seems fine. I wonder if it wouldn't be a good idea to forcefully disable it.
As a side note, the problem wasn't at QS start, it was during the periodic rescan.
Mind: I had a HUGE history - I have 2 MACs always on and in sync, plus 2 iPhones. The end result was an 11k+ item history. I cleaned it before re-opening QS and Safari needed 5 minutes to erase it (!).

Just a wild guess. What happens if QS doesn't complete an index rescan before the next scheduled one happens? I.e., if the rescan interval is 10 minutes, it's every 10 minutes or 10 minutes after the end of the last scan?
What could happen if you start a scan when the old one is still in progress?

**Comment by skurfer** [comment]
> if the rescan interval is 10 minutes, it's every 10 minutes or 10 minutes after the end of the last scan?

Every 10 minutes.

> What could happen if you start a scan when the old one is still in progress?

Each entry keeps track of whether or not it’s scanning. When each scan starts, the first thing it checks is if there’s a scan in progress. If so, it immediately stops.
