### ISSUE TITLE
Safari History catalog source causes Quicksilver to hang

### ISSUE THREAD

**Issue by BluesBrother** [quicksilver/Quicksilver#2331]
I'm running QuickSilver 1.5.2 (401D) on a Mac with El Capitan (10.11.6).

Periodically (about once a week) QuickSilver goes into a loop, consuming high CPU (85% or more). The only work-aournd is to force/cancel it and restart it.

Is this a known problem? As far as I know, I'm on the latest available version of QS.

Thanks!

**Comment by skurfer** [comment]
> Is this a known problem? As far as I know, I'm on the latest available version of QS.

A new version was released yesterday. I can’t promise it fixes your problem, but it fixes a lot of hangs like the ones you describe.

**Comment by lehmacdj** [comment]
I am also experiencing this but on 1.5.3.

Here is a sample of quicksilver while it is crashing: [qs_1.5.3_sample.txt](https://github.com/quicksilver/Quicksilver/files/859357/qs_1.5.3_sample.txt)

I updated a few days ago when I saw that 1.5.3 was supposed to fix these problems.

**Comment by skurfer** [comment]
Safari History again. I suppose you should just disable it for now. We’ll continue to investigate. Thanks.

**Comment by lehmacdj** [comment]
This seems to have fixed the issue. Thanks!

**Comment by BlazZupan** [comment]
Thanks! I had a similar problem and the new version fixed this.

**Comment by Howmuch** [comment]
same issue, disable Safari History fixed the issue

**Comment by skurfer** [comment]
See if this work-in-progress build is any better when Safari History is enabled. Thanks.

https://cl.ly/3a0e0v0j210e

**Comment by Howmuch** [comment]
Still hang

Here is a sample of quicksilver while it is looping:
[Sample of Quicksilver.txt](https://github.com/quicksilver/Quicksilver/files/876231/Sample.of.Quicksilver.txt)

**Comment by pjrobertson** [comment]
> Safari History again. I suppose you should just disable it for now. We’ll continue to investigate. Thanks.


Should we just disable the ability of Safari history to add items to the catalog, or limit the number to the most recent 100?

**Comment by skurfer** [comment]
The problem comes from `assignURLTypesForURL:`. Safari History just makes it obvious by calling that thousands of times.

I’d rather fix it “for real” if we can. In this case, I think it’s just a matter of having `QSUTIForAnyTypeString()` return the type unchanged for a few where we already know that’s what will happen, like “Apple URL Pasteboard Type”. This short-circuits all the UTI code that seems to be hanging lately. That’s what I did in the test build above.

The most recent hang above wasn’t from that. It looks like @Howmuch was in the Catalog prefs, which was trying to display a count for Safari History, but that entry was also being scanned at the time on another thread. Both threads locked up asking if the catalog entry is enabled for some reason.

**Comment by pjrobertson** [comment]
> I’d rather fix it “for real” if we can. In this case, I think it’s just a matter of having QSUTIForAnyTypeString() return the type unchanged for a few where we already know that’s what will happen, like “Apple URL Pasteboard Type”. This short-circuits all the UTI code that seems to be hanging lately. That’s what I did in the test build above.

I think we fixed this in e18ac4513ea6c987856e232af117f28c7831d5a8 

I only have ~200 items in my safari history, but they seem to load pretty fast in 2.1.0. Will close this now, but if people are still experiencing hangs with the latest version of Quicksilver, please re-comment and we'll open the issue again.

**Comment by skurfer** [comment]
Catching up on old discussions obviously, but I just tried right-arrowing into Safari History and it loaded almost instantly with 1,400+ items. 👍🏼
