### ISSUE TITLE
Feature request for plugin

### ISSUE THREAD

**Issue by D-elias** [quicksilver/Quicksilver#2332]
Can you please make a Quicksilver plugin for the King James Bible?

**Comment by skurfer** [comment]
I don’t think anyone’s ever made a plug-in upon request. (Ask the Sparrow users.) Every plug-in in existence today was created by someone that wanted to use it themselves.

There’s this of course, if you’re motivated to attempt it.

http://projects.skurfer.com/QuicksilverPlug-inReference.mdown

You might be able to get something pretty decent without making a plug-in, though. Quicksilver can index all of the links found in HTML (local or remote) when you right arrow into a URL or use the Show/Search Contents actions.

So if you had a web-based version of the Bible that was laid out in a particular way, you could potentially create a trigger for <top level URL> ⇥ Search Contents. Assuming this would be a list of books, you could then right-arrow further to get more specific until you get to a verse.

You might also be able to add links to the books to the catalog automatically. There’s no UI to configure it, but it is possible to have a catalog entry that pulls links from a URL. You could add one of these to your `Catalog.plist` manually. (For a hint, see the Web Searches presets.)

**Comment by D-elias** [comment]
Thanks for the detailed information. I figured a plug-in would be seamless compared to just looking a verse up with Quicksilver. Would you be interested personally in creating a Quicksilver king James bible plug-in for $100 cash sent to your PayPal account? 

Regards,
Elias












The greater the sacrifice, the greater the freedom!
The soldier died for your freedom, Jesus died for your soul. (Eternal freedom)

**Comment by skurfer** [comment]
> Would you be interested personally in creating a Quicksilver king James bible plug-in for $100 cash sent to your PayPal account?

Heh. I appreciate the enthusiasm, but It’s time I lack, not money. I’m happy to answer any questions if you try to come up with a trigger, catalog entry, or full blown plug-in on your own.

**Comment by D-elias** [comment]
OK I'll give it a shot. I would like it  something simple like Quicksilver: predictive• arrow key-Book/chapter/verse navigation• QuickLook equals large text• return equals large text and start speaking• comma trick plus return equals multiple versus read out loud and large text. 

Do you think this is something that I could do without having any prior experience?

Regards,
Elias












The greater the sacrifice, the greater the freedom!
The soldier died for your freedom, Jesus died for your soul. (Eternal freedom)

**Comment by skurfer** [comment]
> arrow key-Book/chapter/verse navigation

Assuming you’ve figured out where the actual data will come from, that shouldn’t be too hard.

See [loadChildrenForObject:](http://projects.skurfer.com/QuicksilverPlug-inReference.mdown#loadchildrenforobject)

> QuickLook equals large text

QuickLook only works on files (not just anything in QS) and is performed by the OS, so for this to work, you would have to

1. Store the text you want to display in a file
2. Create a custom QuickLook generator that shows large text (instead of the normal text file preview)

> return equals large text and start speaking
> comma trick plus return equals multiple versus read out loud and large text

There is no action in QS that does both Large Type and Speak Text and it’s not possible to run two actions simultaneously, but you could create a new action that does both together. That shouldn’t be too difficult since you can just steal from the existing ones.

[The second part](http://projects.skurfer.com/QuicksilverPlug-inReference.mdown#the-comma-trick) is pretty easy.

> Do you think this is something that I could do without having any prior experience?

It might be a pretty tall order. Maybe if you started with just getting the stuff into Quicksilver as plain text objects, where you get all the existing text actions for free, that would be a good start.
