### ISSUE TITLE
Assign Abbreviation action fails with notification

### ISSUE THREAD

**Issue by anatomatic** [quicksilver/Quicksilver#2350]
When I assign an abbreviation with the "Assign Abbreviation..." action (in this case, assign "afx" to Adobe After Effects) Quicksilver raises a notification:

> Unable to assign abbreviation 'afx' to object Adobe After Effects CC 2017.app. Perhaps you want to create a synonym?

Have abbreviations been deprecated in favor of synonyms? Read up on issue #2301 and this seems to be different, as changing the search reset has no effect.

Edit: macOS Sierra 10.12.4, Quicksilver 1.5.3 (401E)

**Comment by skurfer** [comment]
> Have abbreviations been deprecated in favor of synonyms?

No, they serve different purposes.

You’re seeing that message because not all of the letters in the abbreviation (specifically the ‘x’) appear in the thing you’re creating the abbreviation for.

Synonyms exist for the case where you want a different name for something. In this case, you could create a synonym for After Effects called “AFX” or one called “After FX”. As long as the synonym contains all three letters in the correct order, you can use the abbreviation “afx” to launch it.

**Comment by anatomatic** [comment]
Makes sense, thanks for speedy reply!
