### ISSUE TITLE
QS Consistently Unresponsive

### ISSUE THREAD

**Issue by RichardKCook** [quicksilver/Quicksilver#2354]
When running QS on my late 2013 15" MacBook Pro using macOS Sierra, QS will consistently become unresponsive after a few calls. I'm not sure what triggers this issue but when pressing the activator keys it doesn't display the prompt and hangs in an unresponsive condition. Activity monitor says that it is using 97-99% of the CPU when I go to force quit it.

**Comment by skurfer** [comment]
Sounds like #2331

I’d recommend disabling the Safari History preset until the next release. (It’s under Preferences → Catalog → Plugins → Safari.)

**Comment by RichardKCook** [comment]
Disabled. Will update on status if problem arises again.

**Comment by RichardKCook** [comment]
So far no issues, seems to have fixed the issue. Are you able to explain why this worked or why having it selected makes it hang?

**Comment by skurfer** [comment]
Something changed in later versions of macOS to make looking up types more expensive. This process is repeated for every URL in your history, which is likely thousands of URLs.

It went unnoticed for a long time because Safari History was broken. Once we fixed it, all sorts of people started seeing hangs.

**Comment by RichardKCook** [comment]
Yea that totally makes sense,  I think I had maybe 3.5K in Safari.
