### ISSUE TITLE
Unable to change modifier keys

### ISSUE THREAD

**Issue by darthrootbeer** [quicksilver/Quicksilver#2361]
First install of QS 1.5.4 on macOS Sierra 10.12.4 (16E195).

I cannot change or edit the modifier at all. Clicking on the box to change the modifier flashes something very briefly. Clicking the Edit button also has the same effect.

Rebooted, no change.

Video clip here:
https://www.youtube.com/watch?v=KAwa0vzlxGU

**Comment by skurfer** [comment]
I can confirm this. Thanks for letting us know.

**Comment by adriandhart** [comment]
I have the same problem. Thanks

**Comment by darthrootbeer** [comment]
Solution for now: Uninstall and reinstall using an older version.

**Comment by skurfer** [comment]
> Solution for now: Uninstall and reinstall using an older version.

Once the shortcut is set, it’ll stick if you use the current version.

**Comment by skurfer** [comment]
Tracked it down to dc1dd3ddbc654049180b2656691233b46ae0cc16 using `git bisect`. Shouldn’t be too hard to fix.

cc @tiennou

**Comment by tiennou** [comment]
Shouldn't yes. I seem to remember doing this because warnings. Care to revert that commit ?

**Comment by skurfer** [comment]
We can, but I’ve been messing with it locally. Do we even need those two lines?

**Comment by tiennou** [comment]
You mean the change, or the actual `case` ? Just reading the code, the bug is caused because the change cause it to catch some "stupid" event like mouse-moved (or even mouse-up), so the loop exits immediately.

Frankly, I have no idea why those cases have a fall-through, and AFAIR the original defines don't work as intended anyway (IOW `switch` doesn't do binary masking).

I say revert, or 🔥 the lines if your local wrangling confirm they're either useless or buggy 😉.

**Comment by skurfer** [comment]
Apple’s documentation all but says “useless” and I see no problems editing shortcuts for activation or triggers without them. I’ll put something together soon.
