### ISSUE TITLE
does not capture first keys, sometimes

### ISSUE THREAD

**Issue by lotdrops** [quicksilver/Quicksilver#2378]
Sometimes (frequently, though) when activating quicksilver and typing in the first letter is not captured by quicksilver (and instead written to whatever text input I was using). Extremely annoying because I have to do the quicksilver search again, and sometimes I don't realise I've modified the code I was editing...
This has been the behaviour for more than 1 month, but not sure how long. It didn't happen before.
I haven't done important changes in the configuration, that I recall.

**Comment by skurfer** [comment]
It sounds like QS might be busy doing something when you call it up. Most of the changes in the past couple of months were about reducing these background freezes though, so that’s puzzling.

Which interface are you using (under Preferences → General → Appearance)? Have you noticed any pattern related to what’s selected when you invoke Quicksilver?

**Comment by lotdrops** [comment]
I use (always used) the Bezel (built in). 
I'm not sure I understand what you mean with what's selected. I think it always has the last thing that I called (or the parent folder, when file is deleted).
If you mean what am I invoking when it fails: generally it is a script, but I think it is 1) what I call the most and 2) because in these scripts having or not having the first letter is critical to what is invoked. To clarify, script is "new safari", so invoked by 'nsa' vs 'sa' that calls regular safari instead (so I definitely realise it's not what I wanted); whereas 'saf' and 'af' both invoke safari.

**Comment by skurfer** [comment]
> I'm not sure I understand what you mean with what's selected. I think it always has the last thing that I called (or the parent folder, when file is deleted).

Yes, I mean what was the last thing selected (which is what will be there when you call QS back up)?

All of the data should be in memory for the selected thing, and I don’t *think* it does any processing before showing the UI, but I could be wrong. So for instance, if you see a delay when an image was selected, or a track in iTunes, that might give us somewhere to look for delays.

(I’m assuming the first keystroke is being missed because the UI hasn’t appeared when you start typing. Let me know if that’s not the case.)

**Comment by lotdrops** [comment]
Usually I have a script or an app in memory, and I've tried calling it with an image or an itunes track and it doesn't seem to make it more likely to happen (the opposite if anything, but it's probably chance).
Regarding whether the UI is there, I'm not sure. I've tried recording with quicktime but the letter that's not captured by Quicksilver and the quicksilver appear in the same frame, so no way tell quick one is there first. I press the keys very shortly after invoking Quicksilver, it's all very fast. But I'm sure that I first press the quicksilver invoking keys and then the search ones.
Also, I press the keys fast always, but the fastest are not necessarily the ones that fail or the slowest the ones that work.

**Comment by skurfer** [comment]
Is this still happening?

**Comment by lotdrops** [comment]
Yes, but I'll format my computer soon, as I have some other issues I've had
for a few years.
Maybe that'll solve everything

**Comment by pjrobertson** [comment]
I think this may be related to #2733
