### ISSUE TITLE
Crash Report: Terminating app due to uncaught exception 'NSGenericException'

### ISSUE THREAD

**Issue by drnic1** [quicksilver/Quicksilver#2379]
Crash report (x2 occurrence)

Application Specific Information:
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'NSRunInformationalAlertPanel may only be invoked from the main thread. Behavior on other threads is undefined.'
terminating with uncaught exception of type NSException
abort() called

Full text attached
[2017-07-03 Quicksilver Crash Report.txt](https://github.com/quicksilver/Quicksilver/files/1119637/2017-07-03.Quicksilver.Crash.Report.txt)

**Comment by getling** [comment]
Following this bug: it just cropped up for me and QS crashes every time on start now. Is there a workaround (manual cache clear, etc) that can make QS usable in the interim while a permanent fix is enqueue?

**Comment by tiennou** [comment]
My hunch is that it's crashing while trying to update (which is good news™). You might want to download and install the update manually.

@skurfer Hence, I'll try to tack on a fix for that on #2383 because it's likely the update system is broken in some cases.

**Comment by skurfer** [comment]
@getling I had this happen a few weeks ago due to some corrupted data in the clipboard history. You might try moving `~/Library/Application Support/Quicksilver/Shelves/QSPasteboardHistory.qsshelf` to your Desktop. If that allows QS to launch, delete the file. If it makes no difference, and you don’t want to lose that history, put the file back.

**Comment by getling** [comment]
@skurfer Unfortunately ~/Library/Application Support/Quicksilver/Shelves/ is empty, so that does not help my situation.

@tiennou Your hunch may be correct, as manually updating from 1.5.4 to 1.5.5 allows me now to launch without encountering an immediate crash.

Thanks both of you for the suggestions.

**Comment by lexinator** [comment]
manually upgrading to 1.5.6 resolved my issue with this particular error message.

**Comment by skurfer** [comment]
Fixed by #1596
