### ISSUE TITLE
how to add /usr/local/bin/geeqie?

### ISSUE THREAD

**Issue by reagle** [quicksilver/Quicksilver#2382]
For some reason, I can't launch geeqie (install from homebrew at /usr/local/bin/geeqie). When I go to add a custom path, finder is opened and at the root level but '/usr' is not shown...?

**Comment by skurfer** [comment]
Finder hides a lot of things it thinks most people don’t need to know about. In any open/save dialogue, you can hit ⇧⌘G and type `/usr/local` for example to browse that folder.

I don’t know if you really want to add all of `/usr/local/bin` to your catalog. If not there are ways to add a single file.

**Comment by tiennou** [comment]
@reagle How is setup the command you're executing ? `geeqie $args` > `Run command in shell` or `geeqie $args` > `Run a text command in Terminal` ? The first one will lack the necessary `$PATH` setup (because GUI apps don't "inherit" from a shell session, hence the various `~/*rc` files are never read). You should be able to use the 2nd though, because it will open in Terminal which will have performed the "login" dance.

**Comment by reagle** [comment]
@skurfer, ah yes, I forgot that, but maybe you are right not to add that whole path.

**Comment by reagle** [comment]
@tiennou I do not understand. I hit `super+space` and type 'geeqie' but it only selects other things.

**Comment by tiennou** [comment]
Sorry, I misunderstood. I was under the impression you were trying to use QS as some kind of command-line interpreter (which is usually how you call things in `/usr/local/bin`). Those 2 actions above allows you to to that.

**Comment by reagle** [comment]
It's just a program, installed by homebrew like so many other programs, but I can't get it to launch via QS. I always have to go to the terminal. I can add a symlink in my ~/bin/ (which is already cataloged) and then it works, but I'm not sure why I have to do this. Maybe it's something to do with the homebrew package.

**Comment by tiennou** [comment]
As ever, there are many way to do things with QS 😉.

The easy one is to get the Terminal plugin installed. That should add the 2 actions above (which you might need to enable in the Actions preference pane). That will allow you to execute arbitrary text (like "geeqie"). You'll have request Text-mode explicitly though, pressing `'` with the 1st pane selected.

The harder way (IMHO) is being able to "select" a real object, which means you have to add `/usr/local/bin` and contents to your catalog (see the Catalog preference pane).

Whichever way you choose, launching a command-line executable via QS won't get you anything better than a Terminal window open, because launching a command line process involves pipes and stuff, and the Terminal does it better anyway.
