### ISSUE TITLE
Extra Scripts Icon Missing El Capitan

### ISSUE THREAD

**Issue by gemabuj** [quicksilver/Quicksilver#2393]
This problem persist after I using Onyx on my mac with OSX El Capitan. Quicksilver's Plugin Extra Scripts (Blacktree) icons such as Quit Visible Apps, Shutdown, Restart & others is missing its icon (icns) & replaced by common apple scripts icon. I try to "Get Info" those scripts and the icons are there. How can we solve this (my aesthetics sense is tingling)? Thank you.

**Comment by skurfer** [comment]
Are they missing in the Catalog Preferences, or in the actual Quicksilver interface?

Only the main interface is really set up to notice (and update itself) when the icons finish loading, so you might not always see them in the preferences.

**Comment by gemabuj** [comment]
Thx skurfer for the reply.
They missing in the actual Quicksilver interface.

**Comment by skurfer** [comment]
Which interface do you use? (see Preferences → General → Appearance)

**Comment by gemabuj** [comment]
I'm using Bezel (built-in).

**Comment by skurfer** [comment]
OK. That one should handle icons correctly. Can you run this in Terminal and let me know the results?

~~~
defaults read com.blacktree.Quicksilver QSFilePreviewTypes
~~~

**Comment by gemabuj** [comment]
The results say: "the domain/default pair (/Users/.../Library/Preferences/com.blacktree.Quicksilver, QSFilePreviewTypes) does not exist"

**Comment by skurfer** [comment]
OK, I see the problem. The default behavior for Quicksilver is to show a Quick Look preview for everything. Most of the time, this is an improvement over a generic icon, but not always. (Preference Panes are a good example.)

You have something on your system that claims it can generate Quick Look previews for AppleScript files, so you’re seeing that preview instead of the icon. You can live with this, or explicitly define a list of types for which Quicksilver should use previews instead of icons.

I’ve been using this list for years and have been pretty happy with the results:

  * Images
  * Video
  * Audio
  * PDFs
  * SSL/TLS Certificates
  * Markdown
  * Calendar data

You can apply that list by running

~~~
defaults write com.blacktree.Quicksilver QSFilePreviewTypes -array public.image public.movie public.audio com.adobe.pdf public.x509-certificate net.daringfireball.markdown com.apple.ical.ics
~~~

**Comment by gemabuj** [comment]
Wow thank you Rob. It works! 
Interesting & clear explanation. 
Thanks again!
