### ISSUE TITLE
Can no longer set keyboard shortcuts for triggers

### ISSUE THREAD

**Issue by arthurgleckler** [quicksilver/Quicksilver#2406]
I have several triggers with keyboard shortcuts associated with them, but Quicksilver will no longer let me add keyboard shortcuts for new triggers.  When I click on the Edit button, something flashes in the shortcut text area, but disappears before I can read it.  No matter what I type, nothing goes into that area, and the keyboard shortcut doesn't work.

I really love having keyboard shortcuts for every app!  I hope this is easy to fix.

Thanks.

Quicksilver 1.5.4 (401F).
MacOS Sierra 10.2.6.

**Comment by skurfer** [comment]
That was a bug in 1.5.4 that was fixed soon after. (Thanks for including your version of QS and macOS.)

Another bug caused QS to crash when a new version was released and it attempted to notify you, so you might not be aware of the fix for your issue. Either download the latest from asap.com, or manually check for updates in Quicksilver’s preferences.

**Comment by arthurgleckler** [comment]
Thank you very much.

Sorry, I should have checked for an update first.

**Comment by cro** [comment]
He means https://qsapp.com I’m sure. 😜

**Comment by skurfer** [comment]
No problem @arthurgleckler. This is the easiest type of bug report. 😄
