### ISSUE TITLE
Firefox plugin not working with Firefox Quantum (57)

### ISSUE THREAD

**Issue by n8henrie** [quicksilver/Quicksilver#2407]
I am not getting any bookmarks pulled in with the new Firefox Quantum (57), but this is also my first time installing the Firefox plugin, so I don't know if it worked with 56 or not.

I *did* have to enable the [browser.bookmarks.autoExportHTML](https://qsapp.com/wiki/Firefox_Module) setting to avoid getting an error about finding `sessionstore.js`. It does still find my Firefox history, just no bookmarks.

**Comment by skurfer** [comment]
It looks like the Firefox plug-in pulls bookmarks from an SQLite database.

https://github.com/quicksilver/Firefox-qsplugin/blob/master/QSFirefoxPlugIn.m#L67

They may have changed the location or layout of that data, or switched to something else entirely.

**Comment by n8henrie** [comment]
Correct, I do have [~/Library/Application Support/Firefox/Profiles/*/sessionstore-backups](https://github.com/quicksilver/Firefox-qsplugin/blob/bdc0646f5abd14d93d293eeb48dd0cab2fe2b85a/QSFirefoxPlugIn.m#L27), but no `recovery.js`, only `recovery.baklz4` and `recovery.jsonlz4`.

**Comment by skurfer** [comment]
That’s for the “Current Web Page”. Bookmarks appear to be kept in `places.sqlite`.

**Comment by DavidShepherdson** [comment]
I'm not currently set up to be able to build Quicksilver/plugins on my machine, but I've had a look through the code linked in the comment above. The SQL queries for extracting history and bookmarks from the `places.sqlite` file still work for me when running them manually against my local Firefox profile (I've tried on two different machines: one on 60.0.2, the other on 61.0.1). So at least in terms of the query/schema level, there's no reason this shouldn't still work with current versions of Firefox.

The other bit of that code for looking at the `sessionstore` files will be less successful; as far as I can tell, the files it looks at are no longer used by 'Quantum'-based versions of Firefox, though they will be still lying around in the profile folder if you've used it with a previous version. (The newer sessionstore files use a compressed JSON format rather than JavaScript per se, but apart from needing to decompress, it doesn't look like this would otherwise be substantially different from what the plugin code is doing at the moment.)

Hopefully I'll get a chance at some point to set up the necessary things on my machine to be able to build the plug-in, at which point I might be able to debug further (though I haven't really done any Objective-C development, so I don't have strong skills in that area… :-)).

**Comment by Booligoosh** [comment]
Here is a workaround, although it doesn't acknowledge bookmark folders so it's really not ideal.

1. Set `browser.bookmarks.autoExportHTML` to `true` in `about:config` in Firefox
2. Go into Quicksilver and create a new File & Folder Scanner, selecting your `bookmarks.html` file (in your Firefox profile folder)
3. Click on the info button for the new bookmarks.html scanner. Where it says "Include Contents", select "HTML Links". That's it!

**Comment by pjrobertson** [comment]
Turns out they didn't change the layout of the `sqlite` file, just we were using a version of sqlite3.c that was eons out of date.

This has now been fixed in the latest version of the Firefox plugin. Please keep an eye out for an update for the plugin from within Quicksilver.

Thank you for reporting this issue!
