### ISSUE TITLE
Run Shell Script with optional arguments via Quicksilver Trigger

### ISSUE THREAD

**Issue by blackberryoctopus** [quicksilver/Quicksilver#2411]
Hello, 
I am attempting to craft a trigger that accepts keyboard input and passes the input to a shell script. 

I have a python script that runs without issue from the commandline and accepts input. It acts upon the parameters passed on the commandline; it works as expected. 

I would like to linkup this script to a QS trigger. 

I have configured a trigger:
![screen shot 2017-11-28 at 17 13 06](https://user-images.githubusercontent.com/33268/33347050-97d158ee-d45f-11e7-9da5-6383a79f47f2.png)

However, when I trigger this command, I am not presented with the QS input dialog. 

I have searched the QS Manual and the Github Issues for a description of a similar user issue but came up empty-handed.

Can anyone provide some help?

**Comment by tiennou** [comment]
Manipulating a program's stdin is (I think, haven't tried) a really hard thing to get right from a GUI application. So unless someone steps up to do it, I fear it's not going to happen.

You might at the very least be able to get QS to launch a Terminal for you (which looks like what you're doing in the screenshot), with your shell command running inside, but not much else.

**Comment by skurfer** [comment]
When you create (or edit) the trigger, just hit ⌘X in the third pane to remove any selection.

The closest we’ve come to documenting that is in [an example web search][1]. You can be forgiven for not finding it.

Give it a try, but I’m afraid it might not work in this case because the third pane is allowed to be empty for that action. If it doesn’t work, we’d need to add _yet another_ “Run” action identical to [the existing one][2], but with `indirectOptional` set to false.

[1]: https://qsapp.com/manual/Preferences/#search-wikipedia
[2]: /quicksilver/Terminal-qsplugin/blob/master/Info.plist#L187

**Comment by blackberryoctopus** [comment]
@skurfer I tried to edit my trigger using the approach you suggested: "hit ⌘X in the third pane to remove any selection."

But unfortunately, the trigger continues to behave the same way and simply runs the python script without capturing user input.

**Comment by skurfer** [comment]
I was afraid of that. You can add a new action to the Terminal plug-in and submit a pull request if you want. The required changes should be confined entirely to the `Info.plist`.

Otherwise, the closest you can probably get for now is to create a trigger for

    searchJira ⇥ Select In Command Window

If you make **Run […]** the default action for executables, that should mean you just need to Tab to the third pane to enter the text. If you use the “Smart” spacebar behavior, it can be shortened to

  1. Trigger
  2. Spacebar
  3. Text
  4. Return
