### ISSUE TITLE
Quicksilver using too much processing

### ISSUE THREAD

**Issue by Browne-Windsor** [quicksilver/Quicksilver#2440]
Two things.

1.  I'm running 10.12.6 and updated fairly recently to QS 1.5.9. Checking something else via Activity Monitor, I've noticed that quite often it seems to monopolise a lot of the CPU time. It works fine, but I suspect this shouldn't be happen and might be causing the fan to run more often than it need. I'm not an IT person and don't know whether it's QS itself or one of the plugins that might be the reason.

2.  Why do people have to join something called GitHub to submit reports rather than just send them to you?

**Comment by mica5** [comment]
I had been experiencing high CPU issues with quicksilver for at least a month. Finally about 1-2 weeks ago I went through my catalog and deleted lots of things I don't use; now the CPU stays low.
I saw in previous tickets that the safari plugin was having high CPU issues #2331. I'm not sure if that was fixed.

**Comment by skurfer** [comment]
It was only the Safari History catalog entry, not the entire plug-in, that needed to be disabled. (Chrome history was handled the same way and potentially suffered the same problems.) It has been vastly improved (#2380), but could still be better.

Make sure you have the current version of Quicksilver (1.5.9) and the Safari and/or Chrome plug-in. You could also try disabling the history entries if you don’t find them useful. (Personally, I think it just adds noise to the catalog. If you really want it, the history can be accessed by right-arrowing into the browser.)

Beyond that, I think most of the CPU use typically comes from scanning which apps are running, just because it happens so frequently.

> Why do people have to join something called GitHub to submit reports rather than just send them to you?

We prefer GitHub for reports of problems so they don’t get lost, but you can always ask questions to see if there’s a known fix first over in [the users’ group](https://groups.google.com/forum/#!forum/blacktree-quicksilver).

**Comment by benfts** [comment]
Dear _Quicksilver Gurus_ ,
I have a similar problem, Quicksilver is taking up __6.38GB__ of Memory as I am writing this.
I can't get to it to disable any catalogue or anything because it won't respond to the keyboard shortcut.

Any suggestions on how I can inform you about more of this issue welcome!
But mainly, how do I get my QS back?

Thanks

![image](https://user-images.githubusercontent.com/38257776/38570241-61a2624e-3cbb-11e8-92d9-d7d9228225c8.png)
[Sample of Quicksilver.txt](https://github.com/quicksilver/Quicksilver/files/1895511/Sample.of.Quicksilver.txt)

**Comment by skurfer** [comment]
@benfts Are you not able to get to the preferences via menus using the mouse? In any case, you could try going back to default settings.

1. Quit Quicksilver
2. Make a backup of `~/Library/Preferences/com.blacktree.Quicksilver.plist`
3. Run `defaults delete com.blacktree.Quicksilver` in Terminal
4. Launch Quicksilver

I’m not sure what would explain that sort of memory use. Do you have any folders being scanned to infinite depth in your catalog? Maybe a huge browser history that’s getting indexed?

**Comment by benfts** [comment]
@skurfer I wasn't able to get to the preferences menus with the mouse because only _Activity Monitor_ showed me that Quicksilver was running. Couldn't get the interface to pop up at all.

Anyway, looking into `~/Library/Application Support/Quicksilver/` I found in `Shevles` a `QSPasteboardHistory.qsshelf` that was nearly 5GB.

![image](https://user-images.githubusercontent.com/38257776/38573770-11f44118-3cc5-11e8-95a9-e1661f7d403a.png)

Re-organizing my preferences now.
Thank you

**Comment by hmelman** [comment]
https://qsapp.com/manual/FAQ/
