### ISSUE TITLE
Quicksilver consuming massive amount of CPU%

### ISSUE THREAD

**Issue by jprint** [quicksilver/Quicksilver#2453]
Hi,
I'm a longtime Quicksilver user, and I've recently noticed that my Mac has exhibited sluggish behavior. When I checked the activity monitor I noticed that Quicksilver is consuming massive amount of CPU% -- sometimes as much as 80%!  I've uncheck many boxes in my preferences, though maybe I need to really purge many more of them.  What would you suggest I to do fix this?
Thanks!
-Josh

**Comment by hmelman** [comment]
See: https://qsapp.com/manual/FAQ/

Howard

**Comment by skurfer** [comment]
Do you have the Safari History or Chrome History presets enabled (under Preferences → Catalog → Plugins)? Those can be pretty active.

**Comment by n8henrie** [comment]
Hi @jprint -- this issue seems to be missing some necessary information for us to track it down, and we haven't heard back from you in quite a while. I'm going to close the issue to help keep our list groomed.

If you're still experiencing this issue, please try upgrading to the most recent release of Quicksilver, and if it persists let us know with as much detail as you can provide, and I'll be happy to re-open!
