### ISSUE TITLE
Sub dirs in Applications won't be rescanned

### ISSUE THREAD

**Issue by Jurek-Raben** [quicksilver/Quicksilver#2509]
**Describe the bug**
If you place applications into subdirs inside the "Applications" folder, Quicksilver won't rescan those subdirs. Only a manual scan will show up any new installed app, for example installed to "/Applications/Audio"

**To Reproduce**
1. Create an "Audio" subdir in Applications
2. Install a new audio software, and then move the .app to Audio subfolder
3. Wait until Quicksilver should rescan
4. It will never realize the new app, until you do a manual rescan. Also adding a cusotm Applications scan entry with a lot of directory depth will not change anything here. Might be, that the rescanning does not work at all, but it is set here to 30min.

**Expected behavior**
The new app should appear in the search results after the next automatic rescan.

**Screenshots**

**What version of macOS?**
10.13.4

**What version of Quicksilver?**
1.6.0 (4025)

**Comment by skurfer** [comment]
That’s one of those paths that gets ignored in the periodic rescan (every 10 minutes by default) because, in theory, it gets rescanned as soon as any changes occur. The code that watches for and responds to changes is quite old and could be failing on newer OSes.

You could try making the `/Applications` entry behave like a regular folder entry and see if it gets rescanned (after 10 minutes). There’s no UI for this setting, so you’ll have to edit the property list.

You can edit the Applications preset directly in `/Applications/Quicksilver.app/Contents/PlugIns/Core Support.qsplugin/Contents/Info.plist` and delete the `watchTarget` line.

<img width="522" alt="Screen Shot 2020-02-07 at 7 20 48 AM" src="https://user-images.githubusercontent.com/154676/74029307-69516080-497a-11ea-9554-6fd42f768026.png">

That will probably upset Gatekeeper, though.

A safer way, but with more steps, is to open the info drawer for the Applications preset, go to the Attributes tab, and click “Create Copy”. Then disable the original preset and enable your copy under Custom. Once that’s done, edit the preset in `~/Library/Application Support/Quicksilver/Catalog.plist` to remove the `watchTarget` bit.

**Comment by Jurek-Raben** [comment]
Ok will try, thanks! I always have gatekeeper disabled 🤣

**Comment by Jurek-Raben** [comment]
Removing "watchTarget" entry did not work. Instead then it does not list any app, even after manual rescan. Also if I then add Applications under custom dirs, apps are listed, yet you cannot run it.
