### ISSUE TITLE
Plugins have hex or float `CFBundleVersion`s

### ISSUE THREAD

**Issue by n8henrie** [quicksilver/Quicksilver#2640]
It looks like `CFBundleVersion`s are [supposed to be `[MAJOR].[MINOR].[PATCH]` formatted](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion?language=objc), but currently the majority are using hex:

```console
$ awk '/CFBundleVersion/ { getline; split($0, arr, /[<>]/); print arr[3] }' **/Info.plist  | head
1C
1.0
12C
25
287
A9
47
45
2
120C
```

Further, `bltrversion` assumes hex and chokes on formats that can't be interpreted as hex: <https://github.com/quicksilver/Quicksilver/blob/9300d8893504ff06debfc61da1fbfe6bf54c4479/Quicksilver/Tools/bltrversion#L38>

For the moment, I propose that we:
- if ambiguous assume hex and increment by 1, which preserves backwards compatibility
- fallback to `[MAJOR].[MINOR](.[PATCH])?` if there are any `.`
    - auto-increment only the rightmost part

Sound OK?

**Comment by pjrobertson** [comment]
Makes sense to me. I hate the hex numbers. But I guess they were considered easier to increment. It looks like your PR chooses to just increment the [PATCH] setting?

As much as I'd like to get rid of the hex strings, it'll be a fair amount of testing work because:

* Server handling - I'm pretty sure the qs0.qsapp.com server currently only handles Hex versions
* In-app updating/checking. The app right now compares version numbers based on hex. We'd need to edit the code to compare based on X.Y.Z format. Then any older QS versions that don't have this code would choke if they got an X.Y.Z format from the update server, but expected a hex.

**Comment by skurfer** [comment]
As part of re-building all of the plug-ins, I started ripping out `bltrversion`. It was failing and has maybe always been more trouble than it’s worth because it took so much fiddling.

1. You would often have to manually adjust the version to avoid bumping it by 50 instead of 1.
2. Xcode changed the order it did things, so you would end up building _before_ the script ran. This meant that the plug-in you built was still using the old version, and that the version in the repo didn’t match the built product. You could get around it by building again, then manually putting the version back 1.

I think it has value as a documentation generator if we can get it working again (and get it to run _before_ the bundle is created).

**Comment by n8henrie** [comment]
> It looks like your PR chooses to just increment the [PATCH] setting?

Yes -- I wasn't sure what the analogous change would be as compared to incrementing an int by 1. Because it runs so frequently, I thought patch update seemed the most appropriate which would allow us to manually make it major or minor when finalizing the version number update.

**Comment by pjrobertson** [comment]
> I think it has value as a documentation generator if we can get it working again (and get it to run before the bundle is created).

This is my thinking. We use bltrversion just for turning Documentation.mdown into HTML for the PLIST.

We either go back to 'manually' updating the plugin version *or* only using Github Actions to build all our plugins, then have a separate script for the Github action that increments the build number.

Regarding this issue, I'm still inclined to say we shouldn't change from HEX to decimal X.Y.Z. Just because it'll break our update server and I don't really want to be messing with that - it's worked well for 10 years and if it aint broke don't fix it.

**Comment by skurfer** [comment]
> We use bltrversion just for turning Documentation.mdown into HTML for the PLIST.

And it should still apply `QS_BACKWARDS_COMPATIBILITY_BREAK`. (Forgot about that feature.) We should rename it, though. Not a big deal since we have to manually add it back to most Xcode projects anyway.

> We either go back to 'manually' updating the plugin version or only using Github Actions to build all our plugins, then have a separate script for the Github action that increments the build number.

I prefer manual since only a human can really determine what the displayed version should be anyway.

> I'm still inclined to say we shouldn't change from HEX to decimal X.Y.Z. Just because it'll break our update server

Agree.

**Comment by pjrobertson** [comment]
> I prefer manual since only a human can really determine what the displayed version should be anyway.

Sounds reasonable to me, but I'm not the one building the plugins 🙈  But you idea might be to adapt what I said [here](https://github.com/quicksilver/Quicksilver/issues/2634#issuecomment-1046558299) and have the github action only trigger on a commit with a commit message like: `UPDATE PLUGIN: 1.9.0`

Then the version number could be gleaned from that.

But again, it might actually be simpler for the time being to stick with just manually building. And it's not like we're going to have to keep rebuilding them all the time (unless Apple decides to release a new architecture every couple of months :/ )

But for this issue specifically: moving to X.Y.Z for CFBundleVersion: we'll stick to #HorribleHex for now.

I'll close this now, but feel free to keep the discussion up on Hex and the Github action building if need be.

**Comment by n8henrie** [comment]
- GitHub has good support for workflows that run only on e.g. pushing a tag
- We could easily create an action that:
    - runs on the push of a tag
    - clones QS (master? latest release?)
    - builds QS
    - replaces the version in Info.plist with that from the tag
    - build the plugin
    - If all succeeds, runs qs-push-plugin using a repo secret for the password

Disadvantage of this would be that we would have to manually keep the tag and the version in sync

Maybe something to think about eventually. Currently I'm running into so many issues just building the plugins that I think this may be a ways off before it would save any effort anyway.
