### ISSUE TITLE
Activation key with space appears as '1' in v2.0

### ISSUE THREAD

**Issue by debugDS** [quicksilver/Quicksilver#2692]
Congratulation for the 2.0 release 👏 

There is still a problem with the space key as a shortcut.
See #2687, #2682, #2662 for more details.
See #2662 for the solution.

By the way @pjrobertson you corrected `kVK_Return` and `kVK_Escape` but this involves `kVK_Space`.

Cheers!

**Comment by pjrobertson** [comment]
Thanks @debugDS for the follow-up. I'm still unable to reproduce this. Can you please:

1. Post a screenshot of the Quicksilver 'command' preference pane that shows the issue
2. Let me know what keyboard layout you are using (System Preferences > Keyboard > Input Sources)

I still can't reproduce, but can confirm this appears to be an issue. Your fix solves the problem (like I did in other commits) but I've noticed that the real cause of the problem is a clash between the unicode and keycode values for a key. That's where we're going wrong I think:
![Screenshot 2022-03-29 at 08 37 26](https://user-images.githubusercontent.com/150431/160509725-d801364c-111a-4cde-bba1-340c57579fc9.png)

**Comment by pjrobertson** [comment]
OK, I found the real (underlying) problem - we were mixing unicodes with keycodes in the `unmappedKeys` struct. I've fixed this now, so these keys should now be working properly.

Thanks for all your help debugDS!

**Comment by debugDS** [comment]
That was fast ;-)
Tx
