### ISSUE TITLE
QS not indexing automatically

### ISSUE THREAD

**Issue by zandwacht** [quicksilver/Quicksilver#2934]
My catalog is set to rescan "every 10 minutes".

That hasn't worked in over a year with several QS versions: after adding an application to my Applications folder (which is checked as a Catalog source) I always need to push the rescan button manually to update the number of indexed applications. I sometimes give it a day but rescan automatically never works.

MacOS 12.6 on intel iMac Pro, QS 2.4.0 (4039)

**Comment by n8henrie** [comment]
I'm seeing the same.

1. `touch /Applications/foobar.app`
2. wait (much longer than config) minutes
3. QS -> `foobar`: no results
4. Look in QS settings -> Catalog -> `/Applications` -> `Contents` -- no `foobar.app`
5. Manually hit the refresh button (bottom right)
6. `foobar.app` now appears in `Contents` and appears in QS as expected

Thanks for reporting!

**Comment by James6M** [comment]
Cross-linking to [the blacktree-quicksilver Google forum thread about a similar issue](https://groups.google.com/g/blacktree-quicksilver/c/gSBmx4upjTU).

**Comment by skurfer** [comment]
The first thing to check is whether this is only affecting entries with “Automatically update when files change” enabled. There were some changes related to that about a year ago, and I suspect it’s less reliable than the manual timer-based method.

**Comment by lgarron** [comment]
It seems I cannot uncheck "Automatically update when files change" for the built-in `/Applications` catalog entry.
<img width="290" alt="Screenshot 2023-05-18 at 20 31 26" src="https://github.com/quicksilver/Quicksilver/assets/248078/684093ec-8f90-4e4d-b276-1650d123603d">

What is everyone doing to work around this?
Creating a manual custom entry for `/Applications`?

It would certainly be annoying to wait 10min for new applications to be available (since I'll usually want to launch them immediately after installing), but it's better than "actually never". 😛

**Comment by James6M** [comment]
Workaround (I can't remember where I found this):
Create a Custom catalog item of the Spotlight type, with the Query kMDItemContentTypeTree == 'com.apple.application'
My vague recollection is that this also worked around some problem caused by the fact that some applications are now actually stored in /System/Applications, and only seem to be in /Applications through some Finder magic.  (Use 'ls' in a terminal: they aren't really there!)  But I can't remember the details, nor confirm whether whatever the issue was has or hasn't been fixed.

**Comment by pjrobertson** [comment]
This should now be fixed thanks to 64344eeab6e95f88d464433fc5c77d8aa62ddf36

We will try to get a new release out soon. Thanks!
