### ISSUE TITLE
Forced fixed-width dates in plugin-list

### ISSUE THREAD

**Issue by HenningJ** [quicksilver/Quicksilver#511]
ß61 changed the date display in the plugin-list from a forced US-format (mm/dd/yyyy) to the format defined in System Preferences -> Language & Text -> Formats -> Dates -> Short.
If this is defined without leading zeros (8/9/11 instead of 08/09/11), the dates in the plugin-list has a very non-uniform look, which distracts from the actual information. You tend to look at the length of the date instead of the date itself.

So, I would like a fixed-width format, depending on the user defined format in the system preferences. So, If the user has defined d/m/yyyy, it should still display dd/mm/yyyy for all dates.

This is how it can look now (depending the system preferences):

![Bad example](http://henningj.com/pluginListBad.png)

This is how I'd like it to look (all dates the same width):

![Good example](http://henningj.com/pluginListGood.png)

Patrick mentioned it might be possible by playing with NSDateFormatter of the IB 'Date Formatter' of that column.

**Comment by tiennou** [comment]
I'm tempted to close this because it's been a long time, and I don't think trying to override the user's short date format is either doable or warranted (I mean, we're talking about human things like dates, some countries doesn't even use `/` as their separator, or even arabic numerals — hello CJK users !).

References (for fun) :
- [1] http://exit109.com/~ghealton/y2k/yrexamples.html
- [2] https://www.youtube.com/watch?v=-5wpm-gesOY
- [3] http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time
- [4] http://unicode.org/reports/tr35/tr35-dates.html

**Comment by pjrobertson** [comment]
I agree. I was never very pro messing with date formats.
@tiennou that Youtube video is a bit over the top (since we're not really dealing with timezones and we can get Cocoa to do all the work!)

We're using the user's preferred preferences and I think this is best.

Aside: Today it's 2016年2月6号 in China, but the day after tomorrow is 2016年二月8号 OR 2016年1月1号 (1/1/2016) for the lunar calendar :-)

**Comment by tiennou** [comment]
Yeah, I was mostly joking (I actually worked A LOT with dates and PHP). It's just that there are cases I never imagined (DST changes +9/-9, *really* ?), so I'm keeping this in mind when I think "oh I can do that".

**Comment by pjrobertson** [comment]
Close?§
