### ISSUE TITLE
QS never finds applications

### ISSUE THREAD

**Issue by sygint** [quicksilver/Quicksilver#742]
For some reason somtimes QS just never finds applications, I type the name of the application and seems to just find some random item with the same letters in it, not in order or anything, just random, its weird

**Comment by dylang-usask** [comment]
I am having problems with this.

Quicksilver 2.4.0 (4039).

Ctrl+Space ... Type "ME" "MESS" or "MESSAGES" ... it does NOT find /Applications/Messages!

Instead, I get garbage results for files I don't care to have catalogued.  ~/dmesg-phi-inst.txt, /Library/Application Support/iStat Menus Support/iStat Menus 6/iStat Menus Status.app, /System/Library/PrivateFrameworks... ....   *NONE* of the results contain /Applications/Messages.app.  

If I drill down, there is no listing for /Applications/Messages.app.  I want Quicksilver to find files in /Applications/ and ~/Applications/.   I *NEVER* want it to go into /Library/Application Support/*; I *NEVER* want it to go into /System/Library/*.... and I don't want files -- the only 'file-like' access I desire is for things like ~/Downloads if I go ctrl+space 'Do' or 'Dow' or 'Down' ... and I get other results like '/System/Volumes/Preboot/*' ... which I absolutely DO NOT WANT.

In the past, I could pull down the list of matches and set the priority or scoring for a match to 100 or default.  The problem is that ... these applications in /Applications/ are not being included in the catalogue.  I have tried restarting Quicksilver.  I have tried telling Quicksilver to rescan its catalogue.  Neither of these work.

Underneath Quicksilver Preferences => Catalog => Applications, I have 'Sources' listed.  The selected options are 'Applications' and 'Applications (User)' -- which I interpret to mean as -- Quicksilver will look in /Applications/* (recursively), and ~/Applications/* (recursively).  But it does not find these files.  It produces 30 results, none of which are relevant!   The only enabled plugin is the 'Calculator Plugin' ... 

This has also occurred with /Applications/Firefox.app ... after restarting Quicksilver a few times, it sometimes will 'find' the /Applications/Firefox.app.  But this is hit-or-miss.

1) Is there no way to (with the restricted settings, where I have specified ONLY the { /Applications, ~/Applications, and ~/Downloads } folders + Calculator plugin, for these erroneous results to be disabled?
2) Why doesn't Quicksilver find the files in the folders I have specifically instructed/configured it to look in?

It's so frustrating, I've actually started to use Spotlight for search!  I'd rather have Quicksilver work, as I've used it for 20-ish years -- but it keeps giving me these incorrect results.  30 results for things I haven't asked it to index, and NO results for the things I have instructed it to index -- despite restarting it, despite doing a catalogue rescan.   :(

**Comment by n8henrie** [comment]
Can you confirm with the latest release? 2.4.2 has been out for a while.

**Comment by dylang-usask** [comment]
Ok.  I just downloaded 2.4.2.  I closed and erased 2.4.0.  I put 2.4.2 in /Applications.  I started it.  The behaviour is identical.

**Comment by dylang-usask** [comment]
What can I do to further troubleshoot this?

**Comment by dylang-usask** [comment]
Another side-bug; if I have Quicksilver up, I can't do Shift-Cmd-3 or Shift-Cmd-4 to capture what it considers "matches."   If I dismiss the Quicksilver UI, S+C+3 and S+C+4 work as advertised.  If I have the Quicksilver UI up, these shortcuts are broken.

**Comment by dylang-usask** [comment]
Machine+OS -- 2018 Intel Mac Mini running Sonoma 14.5.

**Comment by dylang-usask** [comment]
Meta-bug -- on the Quicksilver website, if I load https://qsapp.com/support.php ... and I select "FAQ
See the [FAQ Page](https://qsapp.com/wiki/FAQ) in the Quicksilver Wiki for a list of Frequently Asked Questions." ... 

https://qsapp.com/wiki/FAQ displays: 
![Screenshot 2024-05-22 at 10 42 33](https://github.com/quicksilver/Quicksilver/assets/2294447/bd99f108-cb23-4c47-b735-2c94edfd069c)

**Comment by dylang-usask** [comment]
Following the instructions on https://qsapp.com/manual/Troubleshooting/ ; I opened Console.  Troubleshooting states, "Start Console.app and you’ll see the console.log displayed, most applications write their information to this log. If there isn’t a left hand pane in the window click the Logs button in the toolbar to make it appear (or use the Show Log List command from the View menu). Make sure the console.log is selected, that’s where Quicksilver writes all its information."

The LHS doesn't list 'Console.log' ... If I select the computer, 'start streaming (may impact system performance)' and filter 'Quicksilver' -- zero results.  
![Screenshot 2024-05-22 at 11 13 07](https://github.com/quicksilver/Quicksilver/assets/2294447/1bd3b53e-85b8-481f-8459-d2897cf511ec)

**Comment by dylang-usask** [comment]
Should I move my report/comments to a new bug (since this one is closed)?

**Comment by n8henrie** [comment]
Yes please -- new issue, and a separate issue for each bug.

For the screenshots of the catalog -- please also expand the right hand sidebar that shows the individual items being indexed. It sure *looks* like your applications are in there.
