### ISSUE TITLE
Feature Request: Spotlight style indexing exclusion

### ISSUE THREAD

**Issue by batmanppc** [quicksilver/Quicksilver#9]
I have a custom catalog setup to index my Documents folder with depth to infinity since the default Documents catalog only scans top-level.

Would be nice if I could specify which directories not to index. Currently if I want to exclude the contents of a handful of folders, I need to uncheck every single file under said folders and then if any files get added, I have to remember to go uncheck them.

Thanks

**Comment by jspiro** [comment]
This one feature I've needed for six plus years and at this point t is the difference between being able to use quicksilver anymore and not. As a developer, third party libraries are intermingled with code we write. I can't index a single node project anymore because node_modules will add 25k files.

Seriously, just this one thing would make quicksilver run so much faster. Global pattern exclusion. NJ ever ever ever index node_modules, thirdparty, etc. This would reduce my catalog size by 80%.

(I did for and try to add it once, but I'm not much of an objective C developer.)

Can I bribe someone to do this over a weekend?

**Comment by skurfer** [comment]
As a general rule, you should never set up a catalog entry that indexes to infinity. It just makes a mess.

Having said that, I don’t know what a Node project looks like, but if the things you want live at the same depth as things you don’t, there isn’t a good solution right now.

I’ll write the code if someone else wants to hook it up to the UI. 😉

**Comment by pjrobertson** [comment]
Would excluding/including files based on extension or UTI work? You can do this right now.

For example, you could exclude all .pyc files or all files with the UTI for a shell script. I’m not sure if that’s enough though.
You’ll need to at least give an example so there’s something to work from… if it’s going to get done we’ll need more info on exactly how you think it should work :)

**Comment by jspiro** [comment]
Happy to see life pop up on here so quickly! =) I just finished playing a rather cerebral and lonely game, so this might be a bit long.

I'm surprised this isn't a feature everyone is screaming to have, I must use QS differently than most people. I've been using it as long as I've had a Mac, I can't live without it, but it's been harder as I work on bigger, more modern projects, as I collect more files, etc.

I don't want to micromanage whole-system search, and I'm not using QS to only search a few locations (why would I want to use a different tool?); that's kind of the point, not needing to spend time knowing what you have nor where it is, but it always being there when you look. Indexing to infinity is ideal (to me); it's the least effort and the richest. But it's not yet practical (not with QS' current database and indexing strategy).

Eliminating individual file extensions doesn't work in e.g. a node project because you have say a dozen javascript files (that you want to find!), and sibling to them is the node_modules folder with 25 packages, each of which is also a node project... you have thousands of javascript files now (and other files you don't want to find of various filetypes).

The minimum that I feel would work is a _global_ list of simple (ideally, regex, if it isn't too slow) patterns (that could also match full file paths) for things to exclude. If a path matches anything in that list, it isn't recursed into or added to the catalog. That's it. (And for symlinks, only follow them if they don't match the pattern, and also check the resolved path.)

That's not user friendly, but revising the QS interface to better support this is way beyond scope or necessity.

Here's how Arq does both at the same time; it's still not the best interface, but both are differently necessary. If you want to quickly one-off remove a folder or item, you can do that by drilling down on the left. If you want to completely remove a pattern you see all over, you can easily do that too.

<img width="846" alt="screenshot 2016-12-06 at 3 57 23 am" src="https://cloud.githubusercontent.com/assets/232896/20925079/8671a80c-bb69-11e6-9f76-80778ab7fc52.png">

Anyway, I appreciate having the discussion to see how my use differs from other people. I <3 QS and would love this, but only if it makes sense for the community. Hopefully I'll have a (professional) reason to pick up ObjC some day ;)

**Comment by studgeek** [comment]
This still doesn't seem to be supported, no commenting to reopen because it would be very handy (and is gap relative to a lot of other software).
